#99 fix use case login
techminds-unipd/docs pull request #100
Opened 2024-12-06 21:09 UTC by cvallott

Let me know se qualcosa non va, ho cercato di mettere una via di mezzo tra il ripetere e il non ripetere. Come descrizione nel changelog metterei "Fix use case login" o qualcosa del genere.

2024-12-07 09:51 UTC, Giuseppe5000 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - l'utente inserisce credenziali errate in @login.
Qui lascierei i punti in cui il sistema fa la verifica, ovvero metterei l'intera procedura.

1. attende esito verifica delle credenziali da UC1.1 e UC1.2;
2. viene visualizzato un messaggio d’errore;
3. viene data la possibilità all’utente di riprovare il login;

(E' la roba che dicevamo ieri)

2024-12-07 09:51 UTC, Giuseppe5000 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     2. se la verifica ha successo viene assegnata una sessione all'utente;
Qui io farei:
1. attende esito verifica delle credenziali da @inserimento-username e @inserimento-password;
2. la verifica ha successo e viene assegnata una sessione all'utente;

Però appunto non so se farlo in questo modo è sbagliato.
Il fatto è che questo è l'happy path e non dovrebbe deviare o avere branch (sempre secondo me).

2024-12-07 09:53 UTC, Giuseppe5000 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Utente.
Qui c'è uno spazio in più.

2024-12-07 09:54 UTC, Giuseppe5000 requested changes
Ci sono un po' di cose che cambierei, che si ricollegano al discorso di ieri su telegram.

2024-12-07 10:57 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - l'utente inserisce credenziali errate in @login.
se fosse invece:
1. l'esito della verifica delle credenziali da @inserimento-username e @inserimento-password non ha successo;
2. viene visualizzato un messaggio d'errore;
3. viene data la possibilità all'utente di riprovare il login.

così andrebbe bene? in tal modo il sistema non deve attendere nuovamente (aveva già atteso in UC1) però come conseguenza dell'esito negativo poi fa le altre due cose. Ha senso?

2024-12-07 13:17 UTC, Giuseppe5000 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - l'utente inserisce credenziali errate in @login.
Si dai ci può stare.

2024-12-07 13:29 UTC, Giuseppe5000 approved these changes

2024-12-08 11:33 UTC, T-Brex approved these changes

2024-12-08 11:34 UTC, merged