User story 4
techminds-unipd/docs pull request #101
Opened 2024-12-07 14:53 UTC by Jacky8703

close #87

2024-12-07 15:56 UTC, cvallott requested changes

2024-12-07 15:56 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   2. attende l'esito del controllo;
qui magari metterei
2. attende l'esito del controllo da @controllo-workflow;

2024-12-07 15:56 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    1. esegue il workflow.
1. esegue il workflow in @esecuzione-workflow.

così mettiamo che l'utente esegue il workflow, ma gli diciamo anche che l'ha "già fatto" e non lo sta rifacendo una seconda volta

2024-12-07 15:56 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    3. continua con l'esecuzione.
toglierei il punto tre

2024-12-07 15:56 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    1. esegue il workflow.
1. esegue il workflow in @esecuzione-workflow.

2024-12-07 15:56 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    4. restituisce il risultato (@vis-risultato-esecuzione).
sul punto due metterei "processa la risposta dell'LLM"

2024-12-07 15:56 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    1. esegue il workflow.
1. esegue il workflow in @esecuzione-workflow.

2024-12-07 15:56 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Utente autenticato.
1. esegue il workflow in @esecuzione-workflow.

2024-12-07 15:56 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Utente autenticato.
1. esegue il workflow in @esecuzione-workflow.

2024-12-07 16:09 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   2. attende l'esito del controllo;
secondo me non serve, alla fine si capisce che si parla del controllo sopra, poi non mi ispira taggare lo stesso UC in entrambe le righe

2024-12-07 16:10 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    1. esegue il workflow.
un pò ricorsivo ma ci posso stare

2024-12-07 16:17 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    1. esegue il workflow.
i know ma non ci è venuto in mente altro di meglio per evitare ripetizioni vere e proprie

2024-12-08 08:52 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - L'utente è autenticato.
va il punto e virgola dopo 'L'utente è autenticato;'

2024-12-08 11:19 UTC, cvallott approved these changes

2024-12-08 11:19 UTC, T-Brex approved these changes

2024-12-08 11:19 UTC, merged