Verbale del 2024-12-09
techminds-unipd/docs pull request #116
Opened 2024-12-09 19:15 UTC by Giuseppe5000

È da un po' che non scrivo verbali, siate clementi :)

2024-12-10 08:53 UTC, Jacky8703 commented on RTB/documenti_interni/verbali/2024-12-09.typ
> +    ([Autoformazione], [#link("https://github.com/techminds-unipd/docs/issues/65")[Issue \#65]: Typescript (Residuo del precendete sprint)]),
Residuo con r minuscola e precedente scritto giusto

2024-12-10 09:00 UTC, Jacky8703 commented on RTB/documenti_interni/verbali/2024-12-09.typ
> +        [#link("https://github.com/techminds-unipd/docs/issues/111")[Issue \#111]: Redigere nuove sezioni Piano di Qualifica],
pdq minuscolo

2024-12-10 09:12 UTC, Jacky8703 commented on RTB/documenti_interni/verbali/2024-12-09.typ
> +        [#link("https://github.com/techminds-unipd/docs/issues/106")[Issue \#106]: Aggiornare piano di progetto [sezione sprint 1]],
parentesi tonde direi

2024-12-10 09:14 UTC, Jacky8703 commented on RTB/documenti_interni/verbali/2024-12-09.typ
> +  durata_luogo: ("14:00", "18:30", "Chiamata Discord"),
c minuscola

2024-12-10 09:23 UTC, Jacky8703 commented on RTB/documenti_interni/verbali/2024-12-09.typ
> +             Durante la riunione sono sorti ulteriori dubbi sui casi d'uso, quindi è stata inviata una mail al docente Cardin per fissare un incotro per chiarirli.#linebreak()
incontro

2024-12-10 09:29 UTC, Jacky8703 requested changes
In generale metterei il nome delle sezioni nei documenti tra virgolette, ad es. Redigere "Processi primari" ..., e scegli se frontend/backend metterli tutti con lettera maiuscola o tutti con lettera minuscola

2024-12-10 12:57 UTC, Giuseppe5000 commented on RTB/documenti_interni/verbali/2024-12-09.typ
> +        [#link("https://github.com/techminds-unipd/docs/issues/111")[Issue \#111]: Redigere nuove sezioni Piano di Qualifica],
Però il nome della issue è scritto in quel modo

2024-12-10 12:57 UTC, Giuseppe5000 commented on RTB/documenti_interni/verbali/2024-12-09.typ
> +        [#link("https://github.com/techminds-unipd/docs/issues/106")[Issue \#106]: Aggiornare piano di progetto [sezione sprint 1]],
Stessa roba, la issue è scritta in quel modo su gh

2024-12-10 14:46 UTC, Jacky8703 commented on RTB/documenti_interni/verbali/2024-12-09.typ
> +        [#link("https://github.com/techminds-unipd/docs/issues/111")[Issue \#111]: Redigere nuove sezioni Piano di Qualifica],
Io manterrei il documento coerente più che le issue, poi non so @leosalvi03 cosa dici

2024-12-10 14:47 UTC, Jacky8703 commented on RTB/documenti_interni/verbali/2024-12-09.typ
> +        [#link("https://github.com/techminds-unipd/docs/issues/106")[Issue \#106]: Aggiornare piano di progetto [sezione sprint 1]],
Si ma perché è stata scritta così? Le parentesi quadre non hanno molto senso

2024-12-10 15:43 UTC, Giuseppe5000 commented on RTB/documenti_interni/verbali/2024-12-09.typ
> +        [#link("https://github.com/techminds-unipd/docs/issues/106")[Issue \#106]: Aggiornare piano di progetto [sezione sprint 1]],
Se vuoi le metto tonde sia qui che sulla issue ed easy

2024-12-10 16:08 UTC, leosalvi03 requested changes
So di essere un po' rigoroso con l'italiano: non prendere alcune correzioni troppo sul serio: sono più osservazioni stilistiche che errori

2024-12-10 16:08 UTC, leosalvi03 commented on RTB/documenti_interni/verbali/2024-12-09.typ
> +        [#link("https://github.com/techminds-unipd/docs/issues/111")[Issue \#111]: Redigere nuove sezioni Piano di Qualifica],
Prediligerei anche io l'uniformità alla coerenza con il nome delle issues.
Basta scegliere come scriverle i nomi dei documenti nei verbali e mantenere quello stile (minuscolo o maiuscolo)

2024-12-10 16:43 UTC, Giuseppe5000 commented on RTB/documenti_interni/verbali/2024-12-09.typ
> +  riassunto: [Il team si è riunito per celebrare lo sprint review e la retrospettiva dello sprint 1, successivamente è avvenuto lo sprint plan dello sprint 2.
Azz hai ragione

2024-12-12 21:02 UTC, leosalvi03 requested changes
A parte un piccolo dettaglio, mi sembra tutto scritto bene

2024-12-13 07:55 UTC, leosalvi03 approved these changes

2024-12-13 08:05 UTC, Jacky8703 approved these changes

2024-12-13 08:07 UTC, merged