Verbale esterno del 11/12/2024
techminds-unipd/docs pull request #123
Opened 2024-12-11 15:27 UTC by Giuseppe5000

2024-12-11 15:53 UTC, leosalvi03 requested changes

2024-12-11 15:53 UTC, leosalvi03 commented on RTB/documenti_esterni/verbali/2024-12-11.typ
> +             Abbiamo concordato che ai fini del progetto il login non è un requisito necessario, visto che l'applicazione potrebbe eseguire in locale sulla macchina dell'utilizzatore e salvando così
- [ ] Terrei l'infinito sostituendo "salvando" con "salvare"
- [ ] Toglierei "così"

2024-12-11 15:53 UTC, leosalvi03 commented on RTB/documenti_esterni/verbali/2024-12-11.typ
> +             Successivamente abbiamo deciso quali funzionalità dovrà implementare il PoC. Abbiamo concordato che basta creare una webapp che permetta di creare dei semplici workflow (semplici nel sen
- [ ] Sostituire "basta" con "basterà" per mantenere il futuro usato nella frase precedente.
- [ ] Volendo, si potrebbe sostituire "basterà" con "sarà sufficiente", ma questo è a tua discrezione. Sostituirei il primo creare con "...realizzare una webapp" per evitare la ripetizione di creare.
- [ ] Spezzerei la frase in due mettendo punto dopo drag&drop per facilitare la lettura.

2024-12-11 15:53 UTC, leosalvi03 commented on RTB/documenti_esterni/verbali/2024-12-11.typ
> +             Riguardo ai prossimi incontri, si cercherà di fissare l'incontro per il Design Thinking a Gennaio e sempre nello stesso mese inizieremo ad evere degli incontri più frequenti (ogni due se
- [ ] Non scriverei "si cercherà di fissare" ma "si fisserà" dato che è la nostra volontà.
- [ ] Metterei una virgola prima e una dopo "sempre nello stesso mese".
- [ ] Correggere evere con avere
- [ ] Metterei direttamente "incontri bisettimanali"
- [ ] Specificherei "di perdere i contatti" piuttosto che "di perderci" e basta

2024-12-11 15:53 UTC, leosalvi03 commented on RTB/documenti_esterni/verbali/2024-12-11.typ
> +    ),
Aggiungerei le decisioni sulla pianificazione degli incontri e del design thinking anche in questa sezione sulle decisioni (senza linkare una issue)

2024-12-11 16:01 UTC, Giuseppe5000 commented on RTB/documenti_esterni/verbali/2024-12-11.typ
> +             Riguardo ai prossimi incontri, si cercherà di fissare l'incontro per il Design Thinking a Gennaio e sempre nello stesso mese inizieremo ad evere degli incontri più frequenti (ogni due se
Bisettimanali vuol dire due volte a settimana però

2024-12-11 16:08 UTC, leosalvi03 commented on RTB/documenti_esterni/verbali/2024-12-11.typ
> +             Riguardo ai prossimi incontri, si cercherà di fissare l'incontro per il Design Thinking a Gennaio e sempre nello stesso mese inizieremo ad evere degli incontri più frequenti (ogni due se
Vero, pardon

2024-12-11 16:16 UTC, leosalvi03 requested changes

2024-12-11 16:16 UTC, leosalvi03 commented on RTB/documenti_esterni/verbali/2024-12-11.typ
> +             Successivamente abbiamo deciso quali funzionalità dovrà implementare il PoC. Abbiamo concordato che sarà sufficiente realizzare una webapp che permetta di creare dei semplici workflow (s
Piuttosto che "Infine" scriverei "Tali workflows dovranno essere eseguibili (o eseguiti, come preferisci) tramite un'agente".

2024-12-11 16:16 UTC, leosalvi03 commented on RTB/documenti_esterni/verbali/2024-12-11.typ
> +             Riguardo ai prossimi incontri, si fisserà l'incontro per il Design Thinking a gennaio e, sempre nello stesso mese, inizieremo ad avere degli incontri più frequenti (ogni due settimane ci
Cambierei "si fisserà" in "fisseremo" o "inizieremo" in "si inizierà" per mantenere la forma verbale

2024-12-11 16:54 UTC, Jacky8703 commented on RTB/documenti_esterni/verbali/2024-12-11.typ
> +             Abbiamo concordato che ai fini del progetto il login non è un requisito necessario, visto che l'applicazione potrebbe eseguire in locale sulla macchina dell'utilizzatore e salvare tutti
è corretto dire "l'applicazione esegue in locale" o "si esegue l'applicazione in locale"? nel senso chi è il soggetto di eseguire

2024-12-11 16:55 UTC, Jacky8703 commented on RTB/documenti_esterni/verbali/2024-12-11.typ
> +             Successivamente abbiamo deciso quali funzionalità dovrà implementare il PoC. Abbiamo concordato che sarà sufficiente realizzare una webapp che permetta di creare dei semplici workflow (s
agente dovrebbe essere maschile quindi senza "un" senza apostrofo

2024-12-11 16:58 UTC, Giuseppe5000 commented on RTB/documenti_esterni/verbali/2024-12-11.typ
> +             Abbiamo concordato che ai fini del progetto il login non è un requisito necessario, visto che l'applicazione potrebbe eseguire in locale sulla macchina dell'utilizzatore e salvare tutti
Il soggetto è l'applicazione (?)

2024-12-11 16:59 UTC, Giuseppe5000 commented on RTB/documenti_esterni/verbali/2024-12-11.typ
> +             Abbiamo concordato che ai fini del progetto il login non è un requisito necessario, visto che l'applicazione potrebbe eseguire in locale sulla macchina dell'utilizzatore e salvare tutti
Quindi il primo caso direi

2024-12-11 16:59 UTC, Giuseppe5000 commented on RTB/documenti_esterni/verbali/2024-12-11.typ
> +             Abbiamo concordato che ai fini del progetto il login non è un requisito necessario, visto che l'applicazione potrebbe eseguire in locale sulla macchina dell'utilizzatore e salvare tutti
Non so se ho compreso bene la domanda

2024-12-11 17:04 UTC, Jacky8703 commented on RTB/documenti_esterni/verbali/2024-12-11.typ
> +             Riguardo ai prossimi incontri, si fisserà l'incontro per il Design Thinking a gennaio e, sempre nello stesso mese, si inizierà ad avere degli incontri più frequenti (ogni due settimane c
magari aggiungi incontri con l'azienda

2024-12-11 17:07 UTC, Jacky8703 requested changes
mancherebbero le s ogni volta che usi workflow al plurale

2024-12-11 17:09 UTC, Jacky8703 commented on RTB/documenti_esterni/verbali/2024-12-11.typ
> +             Abbiamo concordato che ai fini del progetto il login non è un requisito necessario, visto che l'applicazione potrebbe eseguire in locale sulla macchina dell'utilizzatore e salvare tutti
si la domanda era più generale nel senso è l'applicazione che esegue? perché io avrei detto che viene eseguita non che esegue

2024-12-11 17:10 UTC, Giuseppe5000 commented
> mancherebbero le s ogni volta che usi workflow al plurale

Se non sbaglio in italiano non si mettono le parole inglesi al plurale

2024-12-11 17:13 UTC, Jacky8703 commented
> > mancherebbero le s ogni volta che usi workflow al plurale
> 
> Se non sbaglio in italiano non si mettono le parole inglesi al plurale, mi pare lo avesse detto anche big T

ok allora devi toglierla anche a riga 17

2024-12-11 17:57 UTC, Giuseppe5000 commented on RTB/documenti_esterni/verbali/2024-12-11.typ
> +             Abbiamo concordato che ai fini del progetto il login non è un requisito necessario, visto che l'applicazione potrebbe eseguire in locale sulla macchina dell'utilizzatore e salvare tutti
Ok ci sta

2024-12-11 20:04 UTC, Jacky8703 approved these changes

2024-12-12 13:51 UTC, leosalvi03 approved these changes

2024-12-12 13:58 UTC, merged