#114 Processi primari - NdP
techminds-unipd/docs pull request #124
Opened 2024-12-11 16:40 UTC by cvallott

Ho aggiunto la sezione 2.1, se vedete TODO scritto è perchè dovrà riferimento ad un sezione che scriverò nella prossima issue.

2024-12-12 08:00 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +Lo standard definisce i processi primari come i processi relativi alle attività fondamentali per la creazione e la gestione del software. La scelta di aderire ad uno standard è dovuta dal fatto che c
è dovuta al fatto che, non "dal"

2024-12-12 08:03 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +I processi primari prendono tale denominazione proprio per il fatto che un progetto è tale se e solo se in esso sono attivi processi primari.
questa frase è un pò contorta, io al massimo terrei anche solo la seconda parte come introduzione quindi "Un progetto ..." però aspetta di sentire cosa dice @leosalvi03 per l'italiano

2024-12-12 08:18 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +Abbiamo deciso di seguire lo standard ISO/IEC 12207: 1995 che definisce i processi di ciclo di vita, ovvero tutti i processi che possono servire per "spostare" lo stato di vita del progetto da un pun
per descrivere i processi di ciclo di vita io scriverei così "ovvero l'insieme dei processi che descrivono e organizzano il software dalla sua concezione iniziale fino al suo ritiro" o simile

2024-12-12 08:26 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +Con lo scopo di ottenere una visione costante ed aggiornata dello stato del progetto e del bilancio, il processo di fonitura include le attività, i compiti e le risorse necessarie per completare il p
fornitura

2024-12-12 08:32 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +Per raggiungere lo scopo andremo quindi a monitorare e documentare il lavoro svolto e per valutare i progressi compiuti, stimare le attività ancora da completare e confrontare lo stato attuale con i
"questo scopo" se lo hai descritto sopra. poi io cambierei la frase in "andremo quindi a monitorare, documentare e valutare il lavoro svolto stimando le attività ancora da completare e confrontando lo stato attuale ..." o simile

2024-12-12 08:36 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +In questa fase, andremo quindi a studiare a fondo il capitolato per identificare i requisiti del Minimum Viable Product (MVP). Questi requisiti vengono poi discussi e concordati con il proponente in
toglierei la virgola e il quindi

2024-12-12 08:41 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +- Garantiscono il rispetto di quanto pattuito.
lettera maiuscola per la regola idk

2024-12-12 08:47 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +    - piano di progetto: documento che ha lo scopo di raccogliere la pianificazione delle attività progettuali, compresi la gestione dei ruoli e il bilancio di sprint in sprint;
comprese perché fa riferimento alle attività che è femminile

2024-12-12 08:49 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +A supporto del processo di fornitura abbiamo deciso di tuilizzare i seguenti strumenti:
utilizzare

2024-12-12 08:51 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +- Typst per la stesura della documentazione, compresi i diagrammi dei casi d'uso, i diagramma di Gantt e le tabelle di bilancio;
i diagrammi di Gantt

2024-12-12 08:53 UTC, Jacky8703 requested changes
presenti alcuni errori e delle frasi che scriverei in modo diverso

2024-12-12 14:23 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +I processi primari prendono tale denominazione proprio per il fatto che un progetto è tale se e solo se in esso sono attivi processi primari.
ce posso sta'

2024-12-12 14:29 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +- Garantiscono il rispetto di quanto pattuito.
non ho capito cosa intendi

2024-12-12 14:31 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +    - piano di progetto: documento che ha lo scopo di raccogliere la pianificazione delle attività progettuali, compresi la gestione dei ruoli e il bilancio di sprint in sprint;
quel 'compresi' include sia 'la gestione dei ruoli' che 'il bilancio di sprint in sprint' quindi credo vada maschile

2024-12-12 14:46 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +    - piano di progetto: documento che ha lo scopo di raccogliere la pianificazione delle attività progettuali, compresi la gestione dei ruoli e il bilancio di sprint in sprint;
Forse hai ragione, lascia così allora

2024-12-12 14:48 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +- Garantiscono il rispetto di quanto pattuito.
Che c'è la regola che dice di usare la maiuscola in un elenco ma come puoi ben vedere non è che abbia sempre senso, come in questo caso. Vedi tu se lasciarla sennò aspetta @leosalvi03

2024-12-12 15:51 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +- Garantiscono il rispetto di quanto pattuito.
i know ma se iniziamo a rompere le convenzioni del WoW è la fine, anche in altri casi abbiamo dovuto tenere come stabili altrimenti veniva un casino

2024-12-12 15:53 UTC, cvallott commented
ho caricato nuove modifiche e nuove parti (seguendo più rigorosamente lo standard)

2024-12-13 08:46 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +2. Preparazione della risposta: definiamo e prepariamo la proposta, una sorta di "risposta alla richiesta proposta";
frase super contorta, usa offerta al posto di proposta all'interno delle virgolette sennò fai molta confusione

2024-12-13 08:47 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +1. Avvio: eseguiamo una revisione dei requisiti studiando a fondo il capitolato, decidendo poi di proporre un'offerta per un determinato capitolato;
"decidendo poi di fare una proposta" so che è simile ma almeno fai capire meglio la frase 2.

2024-12-13 08:52 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +7. Consegna e completamento: consegnamo il prodotto software al proponenete secondo quanto accordato in precedenza.
consegniamo

2024-12-13 08:56 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-di-supporto.typ
> +I processi di supporto rappresentano un insieme di attività trasversali che aiutano a garantire la qualità e l'efficacia dei processi principali e organizzativi. Le attività descritte all'interno di
"l'efficacia dei processi principali e organizzativi", intendevi primari o volevi scrivere proprio principali?

2024-12-13 09:26 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +2. Preparazione della risposta: definiamo e prepariamo la proposta, una sorta di "risposta alla richiesta proposta";
è venuta così perchè traducendola dall'inglese (lo standard è in inglese) si ottiene quello altrimenti perdeva di senso. se la formulassi tipo: "Preparazione della risposta: elaboriamo e predisponiamo la proposta, ossia una sorta di "risposta alla richiesta avanzata" andrebbe meglio? con offerta si perde un po' il senso secondo me

2024-12-13 09:32 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-di-supporto.typ
> +I processi di supporto rappresentano un insieme di attività trasversali che aiutano a garantire la qualità e l'efficacia dei processi principali e organizzativi. Le attività descritte all'interno di
principali, però è un po' ambiguo quindi tolgo

2024-12-13 09:56 UTC, leosalvi03 requested changes

2024-12-13 09:56 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +    - piano di qualifica: documento che ha la funzione di cruscotto di qualità, contenente quindi le metriche e le normative che abbiamo individuato e adottato;
Il piano di qualifica funge da cruscotto? Ossia mi permette di monitorare in tempo reale le metriche stabilite?

2024-12-13 09:56 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +    - glossario: documento utile per definire termini chiave, ai fini di allineamento interno nella gestione della documentazione;
Io direi "...termini rilevanti nell'ambito del progetto, al fine di uniformare la conoscenza dei membri del gruppo ed evitare incomprensioni e ambiguità".
Non penso che il glossario serva solo ad allineare le conoscenze per la documentazione

2024-12-13 10:04 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +- #text(weight: "bold")[Documentazione interna (propedeutica al gruppo)]:
che è documentazione che serve a noi (o almeno dovrebbe), non scritta per qualche vincolo (poi di fatto è così) ma il suo scopo sarebbe scriverla per noi, tipo il glossario

2024-12-13 10:08 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +    - piano di qualifica: documento che ha la funzione di cruscotto di qualità, contenente quindi le metriche e le normative che abbiamo individuato e adottato;
teoricamente dovrebbe avere quella funzione, ma per evitare rogne sistemo la frase

2024-12-13 10:11 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +    - norme di progetto: il presente documento, creato per identificare il way of working che ci guida nel corso del progetto.
metto  determinare  altrimenti era una ripetizione da sopra

2024-12-13 10:19 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +2. Preparazione della risposta: definiamo e prepariamo la proposta, una sorta di "risposta alla richiesta proposta";
si va bene, bastava non usare proposta che faceva confusione

2024-12-13 12:01 UTC, leosalvi03 requested changes

2024-12-13 12:01 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +Sono stati quindi concordati dei canali di comunicazione che permettono il raggiungimento degli obiettivi sopra descritti (vedi sezione TODO per ulteriori approfondimenti).
Non porterei in main un documento con scritto TODO. Toglierei ciò che è tra parentesi e lo aggiungerei quando la sezione sarà stata scritta.

2024-12-13 12:10 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +Il processo primario di fornitura è focalizzato sulle attività che coinvolgono noi e il proponente durante la fornitura del prodotto software; oltre alle attività sono presenti le risorse necessarie
le docs e gli strumenti utilizzati, se scrivo "le risorse necessarie per portare a termine con successo i processi primari" è meglio?

2024-12-13 12:12 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +Sono stati quindi concordati dei canali di comunicazione che permettono il raggiungimento degli obiettivi sopra descritti (vedi sezione TODO per ulteriori approfondimenti).
ok speriamo di ricordarci poi

2024-12-13 12:51 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/introduzione.typ
>  Il suo scopo è quello di garantire che tutti i membri del gruppo abbiano la stessa base di conoscenza e per sua natura è in continuo aggiornamento.
@cvallott intendevo tra virgole, non tra virgolette. Quindi verrebbe , per sua natura,

2024-12-13 12:54 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +Il processo primario di fornitura è focalizzato sulle attività che coinvolgono noi e il proponente durante la fornitura del prodotto software; oltre alle attività sono presenti le risorse necessarie
Allora non metterei il punto e virgola ma una semplice virgola

2024-12-13 15:02 UTC, leosalvi03 requested changes

2024-12-13 15:10 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/introduzione.typ
> +Il suo scopo è quello di garantire che tutti i membri del gruppo abbiano la stessa base di conoscenza e ,per sua natura, è in continuo aggiornamento.
esplodo, hai ragione

2024-12-13 15:27 UTC, leosalvi03 approved these changes

2024-12-13 17:20 UTC, Jacky8703 approved these changes

2024-12-13 17:22 UTC, merged