#120 correzione casi d'uso
techminds-unipd/docs pull request #125
Opened 2024-12-11 17:09 UTC by MatteoSquarz

Ora abbiamo uc6, uc7, uc8

2024-12-12 09:04 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. avvia la procedura di associazione di un account Google;
. al posto di ;

2024-12-12 09:05 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +- *Descrizione*:
questa nuova sezione non sono così convinto che si possa mettere, se la struttura di un caso d'uso è prestabilita non si può modificare a piacimento, se lo facciamo è da decidere insieme

2024-12-12 09:09 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. avvia la procedura di associazione di un account Google;
. al posto di ;

2024-12-12 09:10 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. l'operazione ha esito negativo.
; al posto di .

2024-12-12 09:11 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - Il sistema notifica l'errore all'utente.
; al posto di .

2024-12-12 09:16 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. rimuove l'account Google associato all'esecuzione dei blocchi nei workflow.
o si spiega anche nell'aggiunta che l'account Google è associato all'esecuzione dei blocchi, oppure si toglie da qui. ; al posto di .

2024-12-12 09:17 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   2. mostra un messaggio di conferma all'utente;
. al posto di ;

2024-12-12 09:19 UTC, Jacky8703 requested changes
alcuni errori di punteggiatura e sezione "Descrizione" da valutare

2024-12-12 09:59 UTC, MatteoSquarz commented
> alcuni errori di punteggiatura e sezione "Descrizione" da valutare

il capo aveva detto di mettere una sezione di descrizione, per quanto riguarda la punteggiatura sono un po sbadato...

2024-12-12 10:04 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +- *Descrizione*:
capiamo con il capo

2024-12-12 10:08 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. rimuove l'account Google associato all'esecuzione dei blocchi nei workflow.
ho messo anche in aggiunta account google

2024-12-12 15:30 UTC, leosalvi03 requested changes

2024-12-12 15:30 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. avvia la procedura di associazione di un account Google.
Questione: specificando questo come scenario non si limita il riuso dello UC? Ad esempio, questo UC si potrebbe riutilizzare nel caso del login con Google

2024-12-12 15:30 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Questo caso d'uso descrive la procedura di rimozione dell'account Google associato all'utente autenticato.
Come prima specificherei che si tratta dell'account Google dei workflow e non di quello dell'accesso

2024-12-12 15:30 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  #figure(
@MatteoSquarz Hai corretto anche lo UC per l'esecuzione dei workflow? Io lo vedo come numero 9 ma non vedo modifiche quindi non capisco se è da considerare in questa PR

2024-12-12 15:30 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  === Esecuzione workflow <esecuzione-workflow>
Nel punto 3 dell'elenco sistema nella sezione "scenario principale" correggere "interfacciarsi ad un LLM" in "interfacciarsi con un LLM"

2024-12-12 15:43 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    node((0,0.5), [#image("../assets/actor.jpg") Utente autenticato], stroke: 0pt, name: <a>),
non facilissimo forse ho migliorato un po la situazione

2024-12-12 15:44 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. avvia la procedura di associazione di un account Google.
meglio non riusarlo e farlo specifico, il login è funzionalità diversa dall'associazione dell'account per i blocchi del workflow

2024-12-12 15:45 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  #figure(
corretto, non ho toccato quello di esecuzione workflow

2024-12-12 15:45 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  === Esecuzione workflow <esecuzione-workflow>
non fa parte di questa pr

2024-12-12 15:46 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  === Esecuzione workflow <esecuzione-workflow>
togliendo uno use case sono scalati tutti i numeri

2024-12-12 22:07 UTC, leosalvi03 requested changes

2024-12-13 07:27 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  - *Pre-condizioni*:
in realtà si potrebbe essere corretto affinchè l'operazione vada a buon fine.

2024-12-13 07:30 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  - *Pre-condizioni*:
quindi in seguito a questa considerazione direi di no forse

2024-12-13 07:35 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +#figure(
Chiaramente una volta associato salviamo nel nostro db l'api key di google, di conseguenza quando rimuovo l'account di google non comunico con google di per sè ma piuttosto elimino dentro il mio db l'account google associato a quell'utente.

2024-12-13 07:35 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +=== Aggiunta account Google associato
ok meglio

2024-12-13 07:39 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +#figure(
ne avevo parlato con Giuseppe proprio di questo ed eravamo arrivati a questa soluzione

2024-12-13 07:50 UTC, MatteoSquarz commented
Mi sento con @T-Brex per quella roba che dici della estensione che si può riusare ma credo che manteremmo cosi

2024-12-13 09:14 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +#figure(
Grazie per la spiegazione!

2024-12-13 09:22 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. avvia la procedura di associazione di un account Google.
effettivamente non ha tutti i torti il saggio, più che altro come abbiamo messo l'errore di comunicazione con Google in questo UC anche in UC3 (Login Google) dovremmo metterlo perché è la stessa questione e a questo punto lo renderei un pò più generale (neanche troppo perché alla fine associare un account o fare il login è la stessa cosa)

2024-12-13 09:28 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. avvia la procedura di associazione di un account Google.
non mi sento di dire che sia sbagliato averne due, anche se nel login google sinceramente non avrei approfondito con casi di estensione vari, si tratta di un requisito opzionale che non faremo mai

2024-12-13 09:34 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. avvia la procedura di associazione di un account Google.
è da decidere, comunque anche le estensioni sono per il riuso "Può esistere indipendentemente dagli use case estesi. Può estendere più use case base (riuso)". con il fatto che l'errore vero e proprio non viene neanche gestito da noi ma dal servizio esterno non è neanche così utile andare nello specifico in entrambi, alla fine ai noi arriverà lo stesso errore

2024-12-13 10:03 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. avvia la procedura di associazione di un account Google.
si ma le precondizioni e postcondizioni sarebbero diverse in realtà si capisce di più se facciamo due casi d'uso diversi secondo me, in un caso la precondizione è che l'utente non è già loggato nell'altro invece che non ha ancora associato un account google per i servizi offerti dai workflow

2024-12-13 10:04 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. avvia la procedura di associazione di un account Google.
io farei un altro caso d'uso con scritto "Errore login Google" se proprio vogliamo farlo

2024-12-13 10:13 UTC, Jacky8703 approved these changes

2024-12-13 11:03 UTC, leosalvi03 approved these changes

2024-12-13 11:04 UTC, merged