fix UC1-UC4
techminds-unipd/docs pull request #126
Opened 2024-12-11 17:57 UTC by T-Brex

close #118
- [x] Aggiunta possibilità di n.m.k come numero del caso d'uso (da n.m)
- [x] separazione login interno e login google
- [x] aggiunta "post-it" per gli extend
- [x] aggiunta "descrizione" per UC in questione
- [x] Correzione . e ;
- [x] modifica attori e pre-condizioni
- [x] aggiunta inset
- [x] correzzione da "-" a "1." negli scenari principali

2024-12-12 09:55 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  node((1.5,1), align(center)[
se il riquadro lo sposti a destra viene più pulito il disegno ad esempio (2.7,1.2)

2024-12-12 10:05 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +- *Pre-condizioni*:
pre-condizioni sbagliate perché un utente può fare il login anche se non ha un account (l'esito sarà negativo), e l'utente non è autenticato lo gestiamo con gli attori (Issue #104)

2024-12-12 10:07 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Login Google (@login-google).
; al posto di .

2024-12-12 10:29 UTC, Jacky8703 requested changes
Su scenario principale di ins. username, pass e login google  sotto utente mettere 1.
Poi in generale ci sono errori che verranno risolti dopo la issue #104 inteoria.

2024-12-12 13:55 UTC, T-Brex commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +- *Pre-condizioni*:
il fatto che l'utente  fa il login anche se non ha account rientra comunque nello UC3 - Credenziali errate?

2024-12-12 14:28 UTC, leosalvi03 requested changes

2024-12-12 14:28 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  - *Scenario principale*:
Mettere 1 al posto del trattino - come marcatore della voce "Inserisce la propria password"

2024-12-12 14:28 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  - *Scenario principale*:
Mettere 1 al posto del trattino - come marcatore della voce "Inserisce il proprio username"

2024-12-12 14:28 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +- *Pre-condizioni*:
Secondo me si può anche tenere la precondizione che l'utente possieda un account. É abbastanza a nostra discrezione. Nel caso in cui non abbia già un account si rientra nel caso della registrazione

2024-12-12 14:28 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  - *Scenario principale*:
In UC3 "Credenziali errate", mettere l'1 al posto del trattino prima di "L'utente inserisce credenziali errate in UC1.1, UC1.2".
Altra questione per cui interrogo anche @Jacky8703: è meglio evitare di specificare i casi d'uso in cui l'utente inserisce credenziali errate? Facendo così si esclude, ad esempio, il caso in cui qualcosa vada storto nella comunicazione con Google e (forse) si rende lo use case più specifico e quindi meno riutilizzabile.

2024-12-12 14:28 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     - richiede di accedere con il proprio account Google.
Cambiare il trattino in 1.

2024-12-12 14:30 UTC, leosalvi03 commented
Osservazione generale: se faccio il login con Google senza essermi mai registrato (né normalmente né con Google) non ho un account ma posso comunque sfruttare le funzionalità di questo use case, non soddisfacendo la precondizione di avere già un account

2024-12-12 14:42 UTC, T-Brex commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  - *Scenario principale*:
Io immaginavo che la parte del Login Google se la gestisce google, quindi
1. l'utente si trova nella procedura di login generica e sceglie la procedura google e viene aperta una nuova finestra gestita da google
- se l'utente, per qualunque motivo non completa il login google, la finestra aperta si chiude e l'utente si ritrova nella schermata di login generico
- se l'utente accede a google viene notificato al nostro applicativo e allora ottiene la sessione e tutt'e cos

2024-12-12 21:26 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  - *Scenario principale*:
@T-Brex @Jacky8703 Effettivamente il mio ragionamento era parzialmente sbagliato. Ci riprovo.
Con l'estensione "Credenziali errate" prevediamo che il login interno possa non andare a buon fine, ma non consideriamo che il login con Google possa non andare a buon fine (anche per motivi tecnici, non solo per problemi di credenziali). Che sia il caso di fare un'estensione anche per prevedere questo caso oppure non è necessario a vostro parere?

2024-12-12 21:38 UTC, leosalvi03 requested changes

2024-12-12 21:38 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> -   - L'utente non è già autenticato.
Come mai hai tolto "L'utente non è già autenticato"?

2024-12-12 21:38 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> -   - L'utente possiede un account;
Immagino tu abbia tolto "L'utente possiede un account" per includere il caso in cui un utente faccia il primo login (di registrazione) con Google. Rivedendolo, ho pensato che forse è meglio tenere questa precondizione (in quanto propria del login). Sorry se ti ho fatto un po' di confusione

2024-12-12 21:38 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  - *Pre-condizioni*:
@T-Brex Secondo te tra le precondizioni dovrebbe esserci anche "L'utente possiede un account Google"? @Jacky8703 che ne pensi?

2024-12-12 21:38 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
@T-Brex hai fatto anche lo UC per la registrazione oppure non lo hai controllato/sistemato?

2024-12-13 07:47 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  - *Pre-condizioni*:
no per i motivi che ti ho scritto nella mia pr

2024-12-13 09:29 UTC, T-Brex commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> -   - L'utente non è già autenticato.
ho cambiato l'attore da utente a utente non autenticato, quindi ho tolto la pre condizione

2024-12-13 09:32 UTC, T-Brex commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> -   - L'utente possiede un account;
l'ho tolto perchè un utente può provare a fare il login anche se non ha un account, però ovviamente il sistema gli darà un errore perchè non trova quelle credenziali
(vedi la conversazione precedente aperta da @Jacky8703 )

2024-12-13 09:35 UTC, T-Brex commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +- *Pre-condizioni*:
Di norma se provi a fare un login a qualunque cosa, il sistema ti dirà sempre "credenziali errate".. quindi il fatto di esporre il fatto che le credenziali non esistano, e quindi fare in modo che il sistema dica di creare un account nuovo, lo vedo come una vulnerabilità di sicurezza

2024-12-13 09:38 UTC, T-Brex commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
no, non ho ancora fatto perchè finchè questa non si risolve non possiamo andare avanti con matteo dato che dovremmo spostare il nostro spazio di lavoro in un nuovo branch "analisi"

2024-12-13 09:50 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  - *Scenario principale*:
> il mio ragionamento a riguardo è subito sopra, se banalmente, la nuova finestra per l'autenticazione google non si apre, rimane la pagina del login generico che verrà aggiornata solo una volta che il login ha successo, sennò rimane sempre lì

si ma devi considerare che per l'associazione account Google abbiamo fatto l'estensione per un qualsiasi errore di comunicazione con i servizi quindi anche in questo caso va fatta. O si toglie in entrambi gli UC o si mette in entrambi per me

2024-12-13 09:58 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  - *Scenario principale*:
in realtà non è detto serva ad entrambi l'errore di comunicazione con google è gestito da google di per sè ma dato che io vorrei vedere anche nel mio sistema un messaggio di errore allora diventa uno use case visto che diventa parte del mio sistema, se invece facciamo che per il login la nostra webapp non fa vedere nessun errore allora secondo me non serve perchè se la gestisce tutta google

2024-12-13 10:01 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  - *Scenario principale*:
ma che motivo hai di vedere un messaggio di errore in un caso e nell'altro no? alla fine anche per l'associazione account se l'utente sbaglia credenziali o altro l'errore viene gestito da Google

2024-12-13 10:06 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  - *Scenario principale*:
beh son robe da decidere in realtà se vuoi che la nostra webapp ti dia un errore anche per il login google che magari non va a buon fine si fa un extend

2024-12-13 10:07 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  - *Scenario principale*:
io non mi andavo a complicare la vita perchè login google è un requisito opzionale e si sa per certo che non lo faremo

2024-12-13 10:12 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> -   - L'utente possiede un account;
forse sarebbe da lasciare affinchè il login abbia successo dato che siamo nell'happy path è necessario che la precondizione sia che l'utente possieda un account... (forse)

2024-12-13 10:16 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> -   - L'utente possiede un account;
per me è corretto così, il secondo punto sistema obbliga la verifica ad avere successo quindi è scontato che l'utente abbia un account

2024-12-13 10:16 UTC, Jacky8703 approved these changes

2024-12-13 11:19 UTC, leosalvi03 approved these changes

2024-12-13 11:20 UTC, merged