Pdp sprint 2
techminds-unipd/docs pull request #129
Opened 2024-12-13 15:07 UTC by Giuseppe5000

close #110

2024-12-13 15:45 UTC, leosalvi03 approved these changes

2024-12-13 17:28 UTC, Jacky8703 commented on RTB/documenti_esterni/piano_progetto/include/costi.typ
> +<tabella-PreventivoSprint1> \
le label sono uguali a quelle dello sprint 1

2024-12-13 17:34 UTC, Jacky8703 requested changes
label vecchie riferite a sprint 1, il resto ok

2024-12-15 12:01 UTC, Jacky8703 approved these changes

2024-12-15 12:05 UTC, merged