Fix generale
techminds-unipd/docs pull request #130
Opened 2024-12-13 15:33 UTC by T-Brex

close #104

2024-12-13 15:56 UTC, leosalvi03 requested changes
Osservazione generale che non mi ricordo se avevo già fatto o solo pensato: non è possibile far rientrare i diagrammi negli stessi margini applicati anche per il testo?
Per il resto (oltre ai due commenti che ho messo), va tutto bene

2024-12-13 15:56 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    ],  name: <b>, inset: 10pt),
Questo nodo ha ancora l'inset. É corretto?

2024-12-13 15:56 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    ],  name: <e>, inset: 10pt),
Questo nodo ha ancora l'inset. É corretto?

2024-12-13 15:56 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    ],  name: <b>, inset: 10pt),
Questo nodo ha ancora l'inset. É corretto?

2024-12-13 16:21 UTC, T-Brex commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    ],  name: <e>, inset: 10pt),
no, grazie per la segnalazione

2024-12-13 16:23 UTC, T-Brex commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    ],  name: <b>, inset: 10pt),
no, grazie per la segnalazione

2024-12-13 16:37 UTC, T-Brex commented
> Osservazione generale che non mi ricordo se avevo già fatto o solo pensato: non è possibile far rientrare i diagrammi negli stessi margini applicati anche per il testo? Per il resto (oltre ai due commenti che ho messo), va tutto bene

@leosalvi03  non ne ho idea

2024-12-13 17:48 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - L'utente ha avviato la procedura di aggiunta account google associato ai workflow (@aggiunta-account-google-associato).
per me questo non è corretto, sei in uno scenario di errore non puoi mettere come precondizione il scenario in cui tutto va bene (anche perché se lo facciamo qui dovremmo farlo su ogni UC in cui è presente un'estensione). In generale io non farei mai riferimento all'UC "generatore" all'interno di un'estensione

2024-12-13 17:49 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - L'utente ha avviato l'esecuzione del workflow (@esecuzione-workflow).
stesso discorso fatto sopra

2024-12-13 17:58 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +- L'utente ha avviato la procedura di registrazione (@registrazione).
manca uno spazio

2024-12-13 18:01 UTC, Jacky8703 requested changes
dubbi su alcuni cambiamenti alle precondizioni

2024-12-14 12:34 UTC, T-Brex commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - L'utente ha avviato la procedura di aggiunta account google associato ai workflow (@aggiunta-account-google-associato).
okay, e quindi come pre-condizione che ci metteresti? forse sarebbe da lasciare vuoto?

2024-12-14 13:18 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - L'utente ha avviato la procedura di aggiunta account google associato ai workflow (@aggiunta-account-google-associato).
ora non so se sia corretto ma prima di poter associare un account ai blocchi bisogna averlo creato il workflow?
perché se così fosse allora metterei la creazione come precondizione

2024-12-14 15:48 UTC, MatteoSquarz commented
Ragazzi c'è un errore logistico questa pr andava fatta alla fine, adesso finchè non chiudiamo questa non posso fare le altre

2024-12-14 15:49 UTC, MatteoSquarz commented
> Ragazzi c'è un errore logistico questa pr andava fatta alla fine, adesso finchè non chiudiamo questa non posso fare le altre

Le correzioni andavamo messe nelle fix specifiche degli uc...

2024-12-14 16:13 UTC, MatteoSquarz commented
NON APPROVARE, PR ERRATA (si va avanti con le pr specifiche per uc)

2024-12-16 15:55 UTC, closed without merging