Processi organizzativi NdP
techminds-unipd/docs pull request #132
Opened 2024-12-14 15:26 UTC by cvallott

close #113

Se vedete che in qualche elenco/sotto-elenco non ho rispettato le regole è perchè sono nomi che devono essere tenuti così (tipo il nome dei canali su discord e telegram, come se fossero dei nomi propri), almeno nella mia testa ha senso così. 

Scusate se è tanto lunga, siate clementi vi prego. Buon lavoro <3

2024-12-15 08:58 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/introduzione.typ
> +- ISO/IEC 12207:1995: https://www.math.unipd.it/~tullio/IS-1/2009/Approfondimenti/ISO_12207-1995.pdf;
per qualche motivo il link sminchia lo spazio

2024-12-15 09:11 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +La politica di rotazione è determinata in accordo tra tutto il gruppo, tenenedo ovviamente conto dei ruoli che non sono ancora stati coperti da ogni membro. Poniamo particolare attenzione al fatto ch
"tenendo ovviamente conto.."

2024-12-15 09:13 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +Infine, durante la fase di scambio dei ruoli, chi ha assunto il ruolo precedentemente, deve "passare la conoscenza" acquisita per aiutare il successore durante il periodo di transizione. Per fare que
passare bruttino, condividere un pò meglio e senza virgolette

2024-12-15 09:19 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +Ruolo chiave in quanto ha lo scopo di controllare la qualità del lavoro svolta dagli altri ruoli e che tale lavoro sia stato eseguito secondo quanto prefissato e concordato dal gruppo e/o da specific
lavoro svolto

2024-12-15 09:22 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +- Typst: utilizzato per la documentazione, i diagrammi di Gantt e la creazione dei diagrammi per gli use cases;
magari metterei creazione dei diagrammi in generale perché ne faremo altri di sicuro e se siamo specifici sarebbero da aggiungere ogni volta

2024-12-15 09:23 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +=== Coordinemanto interno
Coordinamento

2024-12-15 09:25 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +Ogni membro inoltre si assume l'impegno di portare a termine le tasks assegnategli principalmente in modo asincrono e, in caso di necessità collaborative, anche in modo sincrono. La gestione individu
non serve la s su task (parole inglesi al plurale in italiano non serve s)

2024-12-15 09:28 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +Per quanto concerne i meetings interni, che solitamente si verificano da remoto, utilizziamo il canale vocale di Discord, suddiviso in 3 canali (Generale, Generale 1 e Generale 2) in caso di necessit
meeting senza s

2024-12-15 09:29 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +Gli incontri interni si verificano periodicamente per effettuare la sprint review, la sprint retrospective e lo sprint planning tra la fine e l'inizio di uno sprint. In caso di necessità si possono f
meeting senza s

2024-12-15 09:32 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +Il coordinamento tra il gruppo e il proponente è fondamentale sia abbastanza frequente per non perdere l'allineamento tra ciò che il proponente richiede e il prodotto finale consegnato. Inoltre ricev
ripetizione di "lavoro svolto", il secondo puoi toglierlo

2024-12-15 09:34 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +Il proponente ha anche aggiunto in questo canale delle figure professionali esperte nelle tecnologie da utlizzare durante lo svolgimento del progetto, in tal modo i nostri eventuali dubbi verranno ri
tecnologie da utilizzare

2024-12-15 09:35 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +I meetings esterni si svolgono su Microsoft Teams. Nella fase iniziale del progetto non sono stati fissati degli incontri periodici in quanto il primo periodo è stato dedicato allo studio delle tecno
meeting senza s

2024-12-15 09:37 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +Abbiamo deciso di adottare un approccio agile nello sviluppo del progetto prendendo ispirazione dal modello Scrum, metologia ben consolidata e utilizzata nel contesto lavorativo. Questa scelta è stat
metodologia

2024-12-15 09:39 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +- Sprint planning: all'inizio di ogni sprint, guidati dal responsabile, definiamo cosa dovremo consegnare al termine del tempo programmato e predisponiamo il repository GitHub con le issues necessari
issue senza s

2024-12-15 09:41 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +==== Milestones e sprint
Milestone senza s

2024-12-15 09:41 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +Il progetto è suddiviso in periodi chiamati milestones e sprint. Tenendo conto della scelta di un modello agile, abbiamo definito questi due concetti:
milestone senza s

2024-12-15 09:43 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +- Sprint: periodi di lavoro con durata fissa, generalmente due settimane, in cui completiamo le attività pianificate rispettando le scadenze. La durata dello sprint è comune a tutto il gruppo e aiuta
"solo in alcuni casi e di *comune* accordo" credo intendessi

2024-12-15 09:43 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +==== Issues
issue senza s

2024-12-15 09:43 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +Utilizziamo le issues di GitHub per tracciare le attività da svolgere all'interno di ogni sprint.
issue senza s

2024-12-15 09:45 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +- Titolo: descrive in modo breve e coinciso lo scopo della issue;
breve e conciso

2024-12-15 09:48 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +- Projects: progetti a cui la issue è associata. Se sono presenti delle dashboards (vedi @dashboard per approfondimenti) associate ad un progetto, le issues associate sanno visibili anche da lì;
togli le s e "le issue associate *saranno* visibili anche da lì"

2024-12-15 09:50 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +Nel caso in cui una issue sia assegnabile fin da subito ad un membro del gruppo si procede completando anche il campo "Assignees". Se invece è una issue che potrebbe essere svolta da più individui pe
le issue di competenza

2024-12-15 09:53 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +- Board: è un sistema visivo che permette di organizzare e tracciare il progresso delle attività. Le motivazione per cui abbiamo scelto questo sistema è che permette a tutti di avere una panoramica c
La motivazione

2024-12-15 09:57 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +  In questo caso ogni issues viene collocata secondo un principio temporale. Una volta presa in carico e una volta terminata l'assegnatario aggiorna le date date di inizio, di stima e di fine per con
una volta terminata, l'assegnatario

2024-12-15 10:03 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +- Typst: linguaggio per creare documenti con formattazione avanzata, utilizzato per la redazione della documentazione, creazione dei diagrammi degli use cases e di Gantt.
stessa cosa detta sopra, magari mettere diagrammi in generale

2024-12-15 10:05 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +  - raccolta di dati storici, tecnici e di valutazione per ottenere un maggiore comprensione dei punti di forza e delle debolezze dei processi impiegati;
"per ottenere *una* maggiore comprensione"

2024-12-15 10:11 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +1. Attuazione del processo: abbiamo individuato, in accordo con il proponente, le tecnologie da studiare attraverso un profondo studio del capitolato. Abbiamo poi creato un piano di formazione;
magari scriverei "attraverso un *approfondimento* del capitolato" giusto per non ripetere studio

2024-12-15 10:11 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +2. Sviluppo del materiale di formazione: il proponenete ci ha fornito delle risorse specifiche per ogni tecnologia e abbiamo trovato alcuni mini-progetti di prova per iniziare a maneggiare le prime t
il proponente

2024-12-15 10:16 UTC, Jacky8703 requested changes
in generale fai CTRL+f su issue per togliere la s perché ad un certo punto mi sono arreso a segnarle

2024-12-15 14:50 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/introduzione.typ
> +- ISO/IEC 12207:1995: https://www.math.unipd.it/~tullio/IS-1/2009/Approfondimenti/ISO_12207-1995.pdf;
penso perchè il testo è giustificato

2024-12-15 14:53 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +Ogni membro inoltre si assume l'impegno di portare a termine le tasks assegnategli principalmente in modo asincrono e, in caso di necessità collaborative, anche in modo sincrono. La gestione individu
figata non lo sapevo, molto meglio così

2024-12-16 15:00 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +- Typst: linguaggio per creare documenti con formattazione avanzata, utilizzato per la redazione della documentazione, creazione di diagrammi, tabelle e grafici.
```suggestion
- Typst: linguaggio per creare documenti con formattazione avanzata, utilizzato per la redazione della documentazione e per la creazione di diagrammi, tabelle e grafici.
```

2024-12-16 15:00 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +Ha lo scopo di stabilire, valutare, misurare, controllare e migliorare il processo del ciclo di vita del software (standard ISO/IEC 12207:1995).
```suggestion
Il miglioramento del processo ha lo scopo di stabilire, valutare, misurare, controllare e migliorare il processo del ciclo di vita del software (standard ISO/IEC 12207:1995).
```

2024-12-16 15:01 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +3. Miglioramento dei processi: a seguito di valutazione e revisione del processo è fondamentale apportare gli eventuali miglioramenti che riteniamo necessari. La documentazione del processo deve esse
```suggestion
3. Miglioramento dei processi: a seguito della valutazione e revisione del processo è fondamentale apportare gli eventuali miglioramenti che riteniamo necessari. La documentazione del processo deve essere aggiornata per rispecchiare il suo miglioramento. Inoltre è importante svolgere le seguenti azioni:
```

2024-12-16 15:03 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +  - raccolta di dati storici, tecnici e di valutazione per ottenere una maggiore comprensione dei punti di forza e delle debolezze dei processi impiegati;
```suggestion
  - raccogliere dati storici, tecnici e di valutazione per ottenere una maggiore comprensione dei punti di forza e delle debolezze dei processi impiegati;
```
per coerenza con le voci sottostanti

2024-12-16 15:07 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +3. Attuazione del piano di formazione: ogni individuo ha attuato il piano di formazione, contattando gli altri membri del gruppo in caso di dubbi. Inoltre abbiamo partecipato a 3 corsi di formazione
```suggestion
3. Attuazione del piano di formazione: ogni individuo ha attuato il piano di formazione, contattando gli altri membri del gruppo in caso di dubbi. Inoltre, abbiamo partecipato a 3 corsi di formazione offerti dal proponente.
```

2024-12-16 15:21 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +I risultati di tutto ciò si concretizzano nel piano di progetto, documento utile per il gruppo ma anche per il committente e per il proponente in quanto fa da "bacheca" a quanto appena descritto.
ho optato per "in quanto funge da presentazione dei processi organizzativi del team." se no c'era una ripetizione della parola "risultati"

2024-12-16 15:25 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +- Attivare canali vocali per uno scambio più immediato;
la prima, ora ho specificato

2024-12-16 15:28 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +- Gestisce relazioni con l'esterno;
messo stakeholder senza s per la roba che ha detto samu sulle parole inglesi

2024-12-16 15:33 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +==== Tecnologie
metto "Tecnologie e strumenti" dappertutto così siamo sereni

2024-12-16 15:40 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +Per raggiungere l'obiettivo di mantenere comunicazioni attive e veloci interne al team ci siamo dotati dei seguenti canali testuali:
intendevo che non ci ghostiamo a vicenda, però come l'hai scritta te va bene comunque

2024-12-16 15:42 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +=== Tecnologie
ho sistemato mettendo "Strumenti e tecnologie"

2024-12-16 16:22 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +=== Coordiamento interno
coordinamento

2024-12-16 16:28 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +=== Coordiamento interno
non so più scrivere, tra mezz'ora sistemo

2024-12-16 16:49 UTC, Jacky8703 requested changes
riga 187 ispezioniamo, riga 222 La motivazione

2024-12-16 17:57 UTC, Jacky8703 approved these changes

2024-12-17 15:06 UTC, leosalvi03 requested changes
Ho verificato fino a 4.1.2.2 perché ho visto che dopo ci sono ancora molti commenti ancora non risolti

2024-12-17 15:06 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +Ogni membro inoltre si assume l'impegno di portare a termine le task assegnategli principalmente in modo asincrono e, in caso di necessità collaborative, anche in modo sincrono. La gestione individua
```suggestion
Ogni membro inoltre si assume l'impegno di portare a termine le proprie task principalmente in modo asincrono e, in caso di necessità collaborative, anche in modo sincrono. La gestione individuale di tali attività è totalmente libera, tenendo comunque in considerazione l'impegno preso nei confronti del gruppo.
```
Sempre per il discorso che in scrum scelgo io le mie task

2024-12-17 15:06 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +  - analisi-dei-requisiti: canale relativo a dubbi o discussioni riguardo l'analisi dei requisiti e relativi use cases;
```suggestion
  - analisi-dei-requisiti: canale relativo a dubbi o discussioni riguardo l'analisi dei requisiti e relativi use case;
```

2024-12-17 15:09 UTC, cvallott commented
> Ho verificato fino a 4.1.2.2 perché ho visto che dopo ci sono ancora molti commenti ancora non risolti

non ho mica capito cosa intendi, le tue le ho fixate tutte ieri, quelle di samuele ancora l'altro giorno...ieri non avevi verificato tutto?

2024-12-17 16:50 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +  - Domande: utilizzato per raccogliere domande generiche.
come ho scritto in descrizione, sono i nomi delle chat cos' come fossero dei nomi propri

2024-12-17 16:55 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +I meeting esterni si svolgono su Microsoft Teams. Nella fase iniziale del progetto non sono stati fissati degli incontri periodici in quanto il primo periodo è stato dedicato allo studio delle tecnol
metto 'svolgeremo' perchè deve essre prima persona

2024-12-17 16:58 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +L'idea di base alle strategie di tipo agile è l'azione della pratica di Continuous Integration (CI) che:
* cri, cri, cri * credo una pratica (?) alla fine è qualcosa che adottiamo e facciamo concretamente (?)

2024-12-17 17:02 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +- Sprint review: viene effettuata alla fine dello sprint, prima della retrospettiva. Ogni membro del team mostra i progressi fatti e gli obiettivi raggiunti durante il periodo appena terminato;
page not found. comunque ho descritto quello che abbiamo fatto la scorsa volta, so che dovrebbe esserci anche l'azienda ma non possiamo dire che c'è stata. non saprei come scriverla

2024-12-17 17:06 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +6. Se l'esito dei verificatori è positivo, la issue viene ufficialmente spostata alla colonna "Done" della dashboard.
aggiunto sopra

2024-12-17 17:08 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +Riteniamo che board e roadmap siano degli stumenti molto validi:
scritto

2024-12-17 17:09 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +- GitHub Board: https://github.com/orgs/techminds-unipd/projects/1/views/1
si ci sono alcune cose che dovremo aggiornare, comuqnue prima di consegnare leggeremo tutto sicuramente e aggiungeremo

2024-12-17 17:10 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +  Dashboard suddivisa in 5 colonne:
si se no non la metteva sotto la voce dell'elenco ma ripartiva il testo normale

2024-12-17 17:12 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +  - Done: issue terminate.
andrebbe con minuscola ma è il nome assegnato alla colonna quindi come una specie di nome proprio

2024-12-17 17:13 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +  Ogni membro del gruppo è tenuto a controllare frequentemente la dashboard per una panoramica della situazione dello sprint e a gestire le attività assegnategli;
si, fa parte della voce dell'elenco principale GitHub Board

2024-12-18 13:53 UTC, leosalvi03 requested changes

2024-12-18 13:53 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +Abbiamo deciso di adottare un approccio agile nello sviluppo del progetto prendendo ispirazione dal modello Scrum, metodologia ben consolidata e utilizzata nel contesto lavorativo. Questa scelta è st
```suggestion
Abbiamo deciso di adottare un approccio agile allo sviluppo del progetto prendendo ispirazione dal modello Scrum, metodologia ben consolidata e utilizzata nel contesto lavorativo. Questa scelta è stata guidata dai numerosi vantaggi che comporta, per esempio:
```

2024-12-18 13:53 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +- Sprint review: viene effettuata alla fine dello sprint, prima della retrospettiva. Ogni membro del team mostra i progressi fatti e gli obiettivi raggiunti durante il periodo appena terminato;
Con Giuseppe avevamo proprio tolto la sezione sprint review dal pdp. Io specificherei che gli avanzamenti vengono mostrati al proponente; penso che da gennaio ciò accadrà

2024-12-18 13:53 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +  - accede alla dashboard e sposta la issue alla colonna "In progress". In alternativa può cambiare lo stato della issue anche modificando il campo "Status";
```suggestion
  - accede alla dashboard e sposta la issue alla colonna "In progress". In alternativa può cambiare lo stato della issue modificando il campo "Status";
```

2024-12-18 13:53 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +6. Se e quando l'esito della verifica è positivo, la issue viene ufficialmente spostata alla colonna "Done" della dashboard.
```suggestion
6. Se e quando l'esito della verifica è positivo, la issue viene ufficialmente spostata nella colonna "Done" della dashboard.
```

2024-12-18 13:53 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +Per le motivazioni sopra descritte abbimo deciso di utilizzare gli strumenti di GitHub project, in particolare:
```suggestion
Per le motivazioni sopra descritte abbimo deciso di utilizzare gli strumenti di GitHub Projects, in particolare:
```
Sopra l'avevi citato così

2024-12-18 14:23 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-organizzativi.typ
> +La sua posizione centrale è dovuta al fatto che svolge l'attività di *pianificazione*, componente fondamentale perché programma un piano d'azione organizzato che mira al raggiungimento degli obiettiv
perchè era un concetto importante

2024-12-18 15:51 UTC, leosalvi03 approved these changes

2024-12-18 16:05 UTC, merged