#122 fix creazione e salvataggio workflow
techminds-unipd/docs pull request #135
Opened 2024-12-14 17:35 UTC by MatteoSquarz

2024-12-14 17:37 UTC, MatteoSquarz commented
ATTENZIONE PER FARE MERGE IN BRANCH ANALISI NON CI SONO REGOLE DI PROTEZIONE, QUINDI NON FARE MERGE SE NON PRIMA CHE I DUE VERIFICATORI ABBIANO FATTO LA LORO REVIEW @leosalvi03 @T-Brex @Jacky8703

2024-12-15 08:23 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     - L'utente ha collegato almeno un account esterno per poter utilizzare i blocchi ad esso associati.
quindi l'utente non può inserire un blocco all'interno di un workflow finché non collega l'account esterno? so che non lo hai scritto tu ma è per capire il funzionamento, perché la questione ricade anche su pre condizioni dello UC per associare un account Google

2024-12-15 08:31 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     - Il workflow dell'utente viene salvato.
altra questione, l'utente può selezionare l'opzione per salvare solo se ha creato un workflow? perché se così fosse allora manca come pre-condizione. Nel caso in cui non serva averlo creato allora è da cambiare "seleziona l'opzione per salvare il workflow che *ha creato*". Come sopra so che non l'hai fatta tu questa parte ma onere degli analisti ora

2024-12-15 11:58 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     - L'utente ha collegato almeno un account esterno per poter utilizzare i blocchi ad esso associati.
sisi confermo questa cosa, nella visualizzazione dei blocchi disponibili vedi solo quelli che hanno l'account collegato

2024-12-15 11:59 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     - L'utente ha collegato almeno un account esterno per poter utilizzare i blocchi ad esso associati.
infatti abbiamo fatto uno uc che però abbiamo tenuto da parte per il momento sulla visualizzazione dei blocchi, in pratica l'idea è di mostrare solo i blocchi che posso effettivamente utilizzare (ossia quelli associati ad un account)

2024-12-15 12:01 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     - Il workflow dell'utente viene salvato.
forse la metterei come pre condizione effettivamente. "L'utente ha disegnato un workflow"

2024-12-15 12:11 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     - Il workflow dell'utente viene salvato.
anche secondo me

2024-12-15 12:18 UTC, Jacky8703 approved these changes

2024-12-16 17:36 UTC, leosalvi03 requested changes

2024-12-16 17:36 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     2. gestisce gli input drag and drop dell'utente.
Gli input sono solo drag and drop? Esempio: se l'utente clicca su un blocco e poi su un altro, potrebbero essere collegati da un arco. Se scrivo il testo su un arco, non sto facendo drag and drop. 
Drag and drop non dice già il come si realizza un requisito? Dubbio anche mio, magari domani lo metto nel daily scrum. Comunque renderei più generica la frase per gestire tutti i possibili input che arriveranno

2024-12-16 17:36 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     3. si ritrova in una nuova schermata in cui può gestire i blocchi e gli archi;
Manca la scrittura dell'azione sugli archi

2024-12-16 17:56 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     2. gestisce gli input drag and drop dell'utente.
mm dubbio vero

2024-12-16 18:00 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     2. gestisce gli input drag and drop dell'utente.
comunque drag and drop no lo terrei gli input sono fatti cosi è una cosa ricavata dal capitolato non che ci siamo inventati noi per dire come lo implementiamo

2024-12-16 18:01 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     2. gestisce gli input drag and drop dell'utente.
in ogni caso è esplicitato alla fine che si può scrivere sugli archi per descrivere una automazione

2024-12-16 18:02 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     3. si ritrova in una nuova schermata in cui può gestire i blocchi e gli archi;
8. per ogni arco può descrivere un'automazione in linguaggio naturale.

2024-12-16 18:37 UTC, T-Brex commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     2. gestisce gli input drag and drop dell'utente.
> comunque drag and drop no lo terrei gli input sono fatti cosi è una cosa ricavata dal capitolato non che ci siamo inventati noi per dire come lo implementiamo

Forse è meglio mantenerlo generico, nulla vieta che si aggiunga un blocco con un semplice click, l'azienda lo vuole drag and drop, ma si possono mettere anche altri modi per farlo
Ma vedete voi, vi lascio giusto la mia considerazione

2024-12-16 18:40 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     2. gestisce gli input drag and drop dell'utente.
ma se lo vuole l'azienda non è una cosa che si deve fare cosi e basta?

2024-12-16 18:42 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     2. gestisce gli input drag and drop dell'utente.
ah ma forse ho frainteso quello che diceva leo, lui faceva più riferimento alla parte del sistema non a quella dell'utente quindi si capisco ora

2024-12-16 21:40 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     3. si ritrova in una nuova schermata in cui può gestire i blocchi e gli archi;
Giusto, svista mia nel fare su e giù per il documento

2024-12-16 21:42 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     2. gestisce gli input drag and drop dell'utente.
@MatteoSquarz sì, intendevo che c'è scritto che il sistema gestisce gli input drag and drop. Io metterei solo gli input dell'utente visto che vi sono anche input non drag and drop

2024-12-16 21:43 UTC, leosalvi03 requested changes
Ecco come cambierei la frase oggetto del thread precedente

2024-12-16 21:43 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     2. gestisce gli input drag and drop dell'utente.
```suggestion
   2. gestisce gli input dell'utente.
```

2024-12-17 09:56 UTC, leosalvi03 approved these changes

2024-12-17 10:16 UTC, merged