Fix uc10 uc12
techminds-unipd/docs pull request #136
Opened 2024-12-14 23:52 UTC by T-Brex

2024-12-15 08:39 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Questo caso d'uso descrive la visualizzazione dell'errore causato dell'avvio dell'esecuzione di un workflow costruito non correttamente.
"dall'avvio" e cambierei la seconda parte in "esecuzione di un workflow non valido" (per rimanere coerente con "controlla che il workflow sia valido")

2024-12-15 08:49 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +=== Visualizzazione risultato esecuzione workflow <vis-risultato-esecuzione-workflow>
quando io l'avevo messo come include non era corretto perché non è l'utente a mostrare il risultato quindi non può essere attore principale (a ricordo del ricevimento con Cardin, ma chiedo conferma a @MatteoSquarz)

2024-12-15 08:50 UTC, Jacky8703 requested changes
un errore ortografico e UC13 da valutare

2024-12-15 10:33 UTC, T-Brex commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Questo caso d'uso descrive la visualizzazione dell'errore causato dell'avvio dell'esecuzione di un workflow costruito non correttamente.
cambiato

2024-12-15 10:43 UTC, T-Brex commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +=== Visualizzazione risultato esecuzione workflow <vis-risultato-esecuzione-workflow>
Io mi ero segnato che non era corretto perchè l'include è una "lente d'ingrandimento" dello UC padre (esecuzione workflow), ma l'esecuzione e la visualizzazione dei risultati del workflow sono due funzionalità diverse, e quindi la visualizzazione non doveva essere un include ma uno UC a parte

La mia domanda è, se non metto l'utente come attore principale che ci metto?

2024-12-15 11:55 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +=== Visualizzazione risultato esecuzione workflow <vis-risultato-esecuzione-workflow>
confermo quello che dice Alessandro ossia la visualizzazione essendo funzionalità diversa dall'esecuzione è uno uc a parte @T-Brex @Jacky8703

2024-12-15 11:56 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +=== Visualizzazione risultato esecuzione workflow <vis-risultato-esecuzione-workflow>
@Jacky8703 quello che intendi tu era più legato alla parte del controllo del workflow che non è uno uc dato che è una cosa che fa solo il sistema e non c'è una vera e propria interazione con l'utente

2024-12-15 12:09 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +=== Visualizzazione risultato esecuzione workflow <vis-risultato-esecuzione-workflow>
ok se siete sicuri mi fido, anche perché effettivamente si può trattare come una visualizzazione errore in cui l'utente fa l'azione che fa scatenare l'evento

2024-12-15 12:34 UTC, T-Brex commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +=== Visualizzazione risultato esecuzione workflow <vis-risultato-esecuzione-workflow>
Perfetto, ho appena pushato la correzione dell'errore ortografico

2024-12-15 14:23 UTC, Jacky8703 approved these changes

2024-12-16 17:27 UTC, leosalvi03 requested changes

2024-12-16 17:53 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Viene mostrato un messaggio all'utente con il risultato dell'operazione.
così pensi al "come", comunque quando l'ho fatto pensavo ad un semplice messaggio di conferma se è andato tutto bene o di errore in caso contrario, quello intendo con risultato dell'operazione, non tanto cosa fa ma com'è andata

2024-12-16 17:54 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +=== Visualizzazione risultato esecuzione workflow <vis-risultato-esecuzione-workflow>
vedi discorsi fatti sopra nella mia revisione, quando l'ho fatto io era un include ma Cardin ha detto non è corretto

2024-12-16 18:29 UTC, T-Brex commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +=== Visualizzazione risultato esecuzione workflow <vis-risultato-esecuzione-workflow>
La visualizzazione del risultato sarebbe un "include", ma ciò non sarebbe corretto dato che la vis. del risultato non è una lente d'ingrandimento dell' "esecuzione del workflow"

2024-12-16 18:32 UTC, T-Brex commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Questo caso d'uso descrive la visualizzazione dell'errore di runtime durante l'esecuzione di un workflow.
io voglio andare a sottolineare che l'esecuzione è del workflow.
Forse dovrei cambiare in "dell'errore a runtime" piuttosto che "dell'errore di runtime"?

2024-12-16 18:32 UTC, T-Brex commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  === Visualizzazione errore runtime <vis-errore-runtime>
è un "extend", dovrebbe andare bene

2024-12-16 18:34 UTC, T-Brex commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Viene mostrato un messaggio all'utente con il risultato dell'operazione.
Deve essere generico, nell'analisi dei requisiti si pensa al "cosa" non al "come"

2024-12-17 15:12 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Questo caso d'uso descrive la visualizzazione dell'errore di runtime durante l'esecuzione di un workflow.
No no, va bene così

2024-12-17 15:21 UTC, leosalvi03 approved these changes

2024-12-17 15:27 UTC, merged