Pdp refactoring
techminds-unipd/docs pull request #137
Opened 2024-12-16 14:10 UTC by Giuseppe5000

Ora gli sprint sono divisi in file dentro alla directory sprint.
Il file costi.typ serve una funzione per recuperare i dati di uno sprint, le info riguardo le ore andranno lì.

2024-12-16 17:14 UTC, Jacky8703 approved these changes
mi fido che la funzione sia giusta se i numeri sono uguali

2024-12-16 17:17 UTC, Giuseppe5000 commented
> mi fido che la funzione sia giusta se i numeri sono uguali

Noccapito, in che senso sia giusta se i numeri sono uguali?

2024-12-16 17:36 UTC, Jacky8703 commented
> > mi fido che la funzione sia giusta se i numeri sono uguali
> 
> Noccapito, in che senso sia giusta se i numeri sono uguali?

nel senso che mi fido del tuo codice visto che i numeri delle tabelle sono uguali a quelli vecchi scritti a mano (preventivi/consuntivi), senza perdere la testa a capire da solo la logica sotto

2024-12-16 21:38 UTC, leosalvi03 requested changes

2024-12-16 21:38 UTC, leosalvi03 commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint1.typ
> +[il #underline("rosso", stroke: 1pt + red, evade: false) indica l'arco di tempo effettevo;],
```suggestion
[il #underline("rosso", stroke: 1pt + red, evade: false) indica l'arco di tempo effettivo;],
```

2024-12-16 21:38 UTC, leosalvi03 commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint1.typ
> +      task("Redazione diagrammi UC", (from: 9, to: 14, style: (stroke: 8pt + gray)), (from: 9, to: 15, style: (stroke: 2pt + red)))
Dato che la redazione della user story 4 era preventivata per finire il 6 dicembre, questa issue generale non dovrebbe essere preventivata per il 6?

2024-12-17 16:39 UTC, Giuseppe5000 commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint1.typ
> +      task("Redazione diagrammi UC", (from: 9, to: 14, style: (stroke: 8pt + gray)), (from: 9, to: 15, style: (stroke: 2pt + red)))
Si ha senso, correggo

2024-12-18 13:57 UTC, leosalvi03 approved these changes

2024-12-18 16:00 UTC, merged