UC Visualizzazione blocchi configurati
techminds-unipd/docs pull request #140
Opened 2024-12-17 15:06 UTC by MatteoSquarz

close #89 
Controllare uc16 e uc17
L'idea è che l'utente quando si reca nella schermata di creazione di un nuovo workflow, visualizza solamente i blocchi disponibili ad essere utilizzati (se non collega l'account di Google non può utilizzare quei blocchi quindi manco glieli faccio vedere o al massimo glieli oscuro per fargli capire che non li può utilizzare)

2024-12-17 20:28 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    1. Avvia la procedura di creazione di un nuovo workflow.
quindi da come l'avete pensato l'utente vuole creare un nuovo workflow e a quel punto gli vengono mostrati i blocchi, che ci può stare, ma la mia domanda è in quale momento si dà la possibilità all'utente di associare l'account google ai vari blocchi? perché o c'è una sezione a parte in cui crea il blocco (?) e lo collega oppure quando seleziona un blocco già esistente

2024-12-17 20:28 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    1. Controlla che ci sia un account Google collegato.
; al posto di .

2024-12-17 20:29 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    2. Trova un account Google collegato.
; al posto di .

2024-12-17 20:32 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    1. Controlla che ci sia un account Google collegato.
; al posto di .

2024-12-17 20:32 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    2. Non trova un account Google collegato.
; al posto di .

2024-12-17 20:32 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - Viene segnalato all'utente che non ha nessun account Google collegato.
; al posto di .

2024-12-17 20:34 UTC, Jacky8703 requested changes
la sezione descrizione non vi piace più?

2024-12-18 07:14 UTC, MatteoSquarz commented
> la sezione descrizione non vi piace più?

no chiedo scusa dimenticanza mia ahah

2024-12-18 07:14 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    1. Controlla che ci sia un account Google collegato.
secondo me no un account per tutto.

2024-12-18 07:16 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    1. Avvia la procedura di creazione di un nuovo workflow.
lo deve collegare prima di andare sulla schermata nuovo workflow, se non lo associa prima non gli mostro i blocchi e gli mando un avviso con scritto "collega il tuo account Google per vedere i blocchi".

2024-12-18 07:17 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    1. Avvia la procedura di creazione di un nuovo workflow.
ci sarà un pulsante per collegare l'account presumo

2024-12-18 07:18 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    1. Avvia la procedura di creazione di un nuovo workflow.
quindi l'idea è prima collego e poi disegno i workflow, anche perchè disegnare workflow senza aver collegato account è inutile

2024-12-18 16:21 UTC, leosalvi03 requested changes

2024-12-18 16:21 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    3. Fa visualizzare i blocchi che un servizio associato nella sezione dei blocchi configurati.
Come mai "Fa visualizzare" e non "Visualizza"?

2024-12-18 16:21 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    3. Fa visualizzare i blocchi che un servizio associato nella sezione dei blocchi configurati.
Manca "hanno"
```suggestion
    3. Fa visualizzare i blocchi che hanno un servizio associato nella sezione dei blocchi configurati.
```
oppure, se preferite

```suggestion
    3. Visualizza solo i blocchi configurati, ossia associati ad un servizio.
```

2024-12-18 16:21 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Questo caso d'uso descrive la visualizzazione di un avviso per notificare all'utente che non ha nessun account Google collegato ai servizi offerti dai blocchi.
Non so se specificherei account Google. Nel caso in cui in futuro si desse la possibilità di collegare un account di un altro provider, questo UC non sarebbe più valido. Invece, questo UC prescinde dal fornitore del servizio (anche in ottica di riutilizzo).

2024-12-18 16:27 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    3. Fa visualizzare i blocchi che un servizio associato nella sezione dei blocchi configurati.
L'utente visualizza mentre il sistema fa visualizzare

2024-12-18 16:28 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Questo caso d'uso descrive la visualizzazione di un avviso per notificare all'utente che non ha nessun account Google collegato ai servizi offerti dai blocchi.
ok si può togliere google

2024-12-18 16:46 UTC, leosalvi03 approved these changes

2024-12-18 19:03 UTC, Jacky8703 approved these changes

2024-12-18 19:03 UTC, merged