Check glossario
techminds-unipd/docs pull request #144
Opened 2024-12-17 16:45 UTC by cvallott

close #107 
cari verificatori, sono stati modificate un po' di cose tipo i termini del glossario con ricerca automatizzata.  Se vede dei termini commentati su alcuni file è stata una cosa necessaria che vedremo come risolvere, intanto trust us.

2024-12-17 20:46 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +4. Pianificazione: revisioniamo i requisiti di acquisizione per definire il quadro per la gestione del progetto e per assicurare la qua#glossario[qualità]lità del prodotto offerto. Tale pianificazion
piccolo inglobamento

2024-12-17 20:47 UTC, Jacky8703 requested changes
lo scopo è solo quello di segnare le occorrenze giusto non di linkarle

2024-12-17 20:51 UTC, cvallott commented
> lo scopo è solo quello di segnare le occorrenze giusto non di linkarle

se vai sulla issue 107 c'è la checklist delle cose da fare. per ora le segnamo con #glossario[parola]

2024-12-18 16:07 UTC, cvallott commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +4. Pianificazione: revisioniamo i requisiti di acquisizione per definire il quadro per la gestione del progetto e per assicurare la qua#glossario[qualità]lità del prodotto offerto. Tale pianificazion
???

2024-12-18 16:30 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +4. Pianificazione: revisioniamo i requisiti di acquisizione per definire il quadro per la gestione del progetto e per assicurare la qua#glossario[qualità]lità del prodotto offerto. Tale pianificazion
devi togliere "qua" e "lità" ai lati

2024-12-18 20:51 UTC, Jacky8703 approved these changes

2024-12-20 10:40 UTC, leosalvi03 approved these changes

2024-12-20 15:00 UTC, merged