UC Logout
techminds-unipd/docs pull request #145
Opened 2024-12-18 12:09 UTC by T-Brex

close #143

2024-12-18 16:50 UTC, leosalvi03 requested changes

2024-12-18 16:50 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - Il logout avviene con successo.
Avrei scritto "L'utente è non autenticato" per evidenziare lo stato del sistema dopo lo scenario più che il corretto completamento dello scenario.

2024-12-18 20:34 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. Disconette l'account dall'applicativo.
Disconnette, manca una n

2024-12-18 20:36 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. Seleziona l'opzione per fare il logout.
; al posto di .

2024-12-18 20:36 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. Fa visualizzare la schermata di conferma del logout.
; al posto di .

2024-12-18 20:37 UTC, Jacky8703 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - Il logout avviene con successo.
Concordo

2024-12-18 20:38 UTC, Jacky8703 requested changes
punteggiatura

2024-12-19 13:26 UTC, leosalvi03 requested changes
I sottoelenchi devono iniziare con la minuscola. Il resto va bene

2024-12-19 13:26 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   2. Conferma il logout.
Sottoelenchi devono iniziare con la minuscola

2024-12-19 13:26 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. Disconnette l'account dall'applicativo.
Sottoelenchi devono iniziare con la minuscola

2024-12-19 18:32 UTC, Jacky8703 approved these changes

2024-12-20 13:26 UTC, merged