Fix creazione workflow vuoto
techminds-unipd/docs pull request #163
Opened 2024-12-23 20:28 UTC by cvallott

close #152 
Cari verificatori, spero di aver compreso bene cosa dovevo fare. Lo scoprirò dalla quantità di commenti :)

2024-12-24 09:30 UTC, MatteoSquarz approved these changes
corretto

2024-12-26 11:23 UTC, leosalvi03 requested changes

2024-12-26 11:23 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  - *Descrizione*
```suggestion
- *Descrizione:*
```
Mancano i due punti. Mi sono accorto che mancano anche in altri UC (15, 16, 20). Inoltre, negli UC 17 e 18 c'è un errore di battitura nella parola "descrizione". Se puoi ed è legale, correggili, grazie

2024-12-26 11:23 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     - L'utente ha collegato almeno un account esterno per poter utilizzare i blocchi ad esso associati.
Ciò significa che l'applicativo non mi permette di creare un workflow vuoto se non ho almeno un servizio collegato? Perché teoricamente potrei creare un workflow vuoto e poi non poterci mettere dentro nulla (ma intanto l'ho creato)

2024-12-26 12:27 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     - L'utente ha collegato almeno un account esterno per poter utilizzare i blocchi ad esso associati.
forse sposterei allora la precondizione su modifica workflow

2024-12-26 13:24 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     - L'utente ha collegato almeno un account esterno per poter utilizzare i blocchi ad esso associati.
e come pre-condizione metto che l'utente ha effettuato il login?

2024-12-26 17:20 UTC, leosalvi03 approved these changes

2024-12-26 17:36 UTC, MatteoSquarz approved these changes

2024-12-26 17:36 UTC, MatteoSquarz commented
aggiungo verificatore e faccio merge

2024-12-26 17:38 UTC, merged