Stesura verbale del 2024-12-23
techminds-unipd/docs pull request #164
Opened 2024-12-23 20:55 UTC by T-Brex

2024-12-24 08:16 UTC, Giuseppe5000 commented on RTB/documenti_interni/verbali/2024-12-23.typ
> +    "1.0.0", "09/12/2024", "Prima versione", team.A,".-.-."
Qui sembra che non sia stata cambiata la data

2024-12-24 09:48 UTC, MatteoSquarz requested changes

2024-12-24 09:48 UTC, MatteoSquarz commented on RTB/documenti_interni/verbali/2024-12-23.typ
> +    "1.0.0", "09/12/2024", "Prima versione", team.A,".-.-."
aggiornare changelog

2024-12-24 09:48 UTC, MatteoSquarz commented on RTB/documenti_interni/verbali/2024-12-23.typ
> +            - lo studio delle tecnologie è stato completato da tutti i componenti del gruppo.#linebreak()
darei un doppio linebreak()

2024-12-24 09:48 UTC, MatteoSquarz commented on RTB/documenti_interni/verbali/2024-12-23.typ
> +      [#link("https://github.com/techminds-unipd/docs/issues/72")[Issue \#72]: Aggiungere termini al glossario(lasciata in sospeso dallo sprint 1)],
non scriverei (lasciata in sospeso dallo sprint 1), era rimasta semplicemente nel backlog

2024-12-24 09:48 UTC, MatteoSquarz commented on RTB/documenti_interni/verbali/2024-12-23.typ
> +             Successivamente abbiamo celebrato lo sprint plan dello sprint 3, che avrà la durata di tre settimane, vista la minore disponibilità dei componenti del gruppo causa festività natalizie.
metterei "a causa delle festività natalizie."

2024-12-24 11:59 UTC, T-Brex commented on RTB/documenti_interni/verbali/2024-12-23.typ
> +      [#link("https://github.com/techminds-unipd/docs/issues/72")[Issue \#72]: Aggiungere termini al glossario(lasciata in sospeso dallo sprint 1)],
però effettivamente è una issue che è stata creata all'inizio del primo sprint (18 novembre) e che ancora non è stata completata, io vorrei evidenziare il fatto, come dovrei fare?

2024-12-24 12:29 UTC, MatteoSquarz commented on RTB/documenti_interni/verbali/2024-12-23.typ
> +      [#link("https://github.com/techminds-unipd/docs/issues/72")[Issue \#72]: Aggiungere termini al glossario(lasciata in sospeso dallo sprint 1)],
si chiaro, ma comunque eviterei in realtà di fare riferimenti al fatto che fosse del primo sprint (direi semplicemente che era "rimasta nel backlog per più del previsto" forse

2024-12-24 13:18 UTC, T-Brex commented on RTB/documenti_interni/verbali/2024-12-23.typ
> +      [#link("https://github.com/techminds-unipd/docs/issues/72")[Issue \#72]: Aggiungere termini al glossario(lasciata in sospeso dallo sprint 1)],
e lo so che è brutto, sembra che non ci siamo dati da fare, però dire che era "rimasta nel backlog per più del previsto" è una verità incompleta, vuol dire tutto e niente. Non so, sarei più per una descrizione chiara, ma a sto punto chiederei un parere al vecchio capo @Giuseppe5000

2024-12-26 10:40 UTC, leosalvi03 requested changes

2024-12-26 10:40 UTC, leosalvi03 commented on RTB/documenti_interni/verbali/2024-12-23.typ
> +             Successivamente abbiamo visionato la Project Board di Github per verificare quali task dovevano essere completati entro fine sprint. Complessivamente sono stati completati la maggior par
```suggestion
             Successivamente abbiamo visionato la Project Board di Github per verificare quali task dovevano essere completati entro fine sprint. Complessivamente sono stati completati la maggior parte dei task.
```
Task è maschile

2024-12-26 10:40 UTC, leosalvi03 commented on RTB/documenti_interni/verbali/2024-12-23.typ
> +             Infine abbiamo creato tutte le issue relative alla documentazione e non solo, sotto segue una lista esaustiva di ciò.
```suggestion
           Successivamente abbiamo celebrato lo sprint plan dello sprint 3, che avrà la durata di tre settimane, vista la minore disponibilità dei componenti del gruppo causa festività natalizie.
           Abbiamo deciso di focalizzare il lavoro di questo sprint sul PoC e sull'analisi dei requisiti.
           Infine abbiamo creato tutte le issue relative alla documentazione e non solo, sotto segue una lista esaustiva di ciò.
```
Questa parte non è allineata al margine sinistro. Per risolvere basta portarla indietro di una tabulazione

2024-12-26 10:40 UTC, leosalvi03 commented on RTB/documenti_interni/verbali/2024-12-23.typ
> +       [#link("https://github.com/techminds-unipd/docs/issues/159")[Issue \#159]: aggiornamento ndp],
```suggestion
       [#link("https://github.com/techminds-unipd/docs/issues/159")[Issue \#159]: Aggiornamento ndp],
```

2024-12-26 10:40 UTC, leosalvi03 commented on RTB/documenti_interni/verbali/2024-12-23.typ
> +        [#link("https://github.com/techminds-unipd/docs/issues/154")[Issue \#154]: fix UC Visualizzazione blocchi configurati e avviso servizi collegati]
```suggestion
        [#link("https://github.com/techminds-unipd/docs/issues/154")[Issue \#154]: Fix UC Visualizzazione blocchi configurati e avviso servizi collegati]   
```
So che il titolo della issue è stato scritto in minuscolo, ma prediligerei l'uniformità del documento

2024-12-26 10:40 UTC, leosalvi03 commented on RTB/documenti_interni/verbali/2024-12-23.typ
> +      [#link("https://github.com/techminds-unipd/docs/issues/72")[Issue \#72]: Aggiungere termini al glossario(lasciata in sospeso dallo sprint 1)],
```suggestion
      [#link("https://github.com/techminds-unipd/docs/issues/72")[Issue \#72]: Aggiungere termini al glossario (lasciata in sospeso dallo sprint 1)],
```
Aggiungere spazio

2024-12-26 10:40 UTC, leosalvi03 commented on RTB/documenti_interni/verbali/2024-12-23.typ
> +      [#link("https://github.com/techminds-unipd/docs/issues/72")[Issue \#72]: Aggiungere termini al glossario(lasciata in sospeso dallo sprint 1)],
Penso che il processo di aggiunta dei termini al glossario dovrebbe essere legato alla risoluzione di altre issue, non di una specifica; del tipo sto facendo qualcosa, trovo una parola importante o che per me era ambigua, la specifico nel glossario. Non lo stiamo facendo, però secondo me idealmente non dovrebbe esserci una issue apposita. Semmai questa issue può diventare per il riallineamento del glossario

2024-12-27 11:54 UTC, T-Brex commented on RTB/documenti_interni/verbali/2024-12-23.typ
> +      [#link("https://github.com/techminds-unipd/docs/issues/72")[Issue \#72]: Aggiungere termini al glossario(lasciata in sospeso dallo sprint 1)],
vabbene per ora ho eliminato (lasciata in sospeso dallo sprint 1)

2024-12-27 15:58 UTC, MatteoSquarz approved these changes
data changelog da cambiare, ma lo faremo noi verificatori

2024-12-27 17:39 UTC, leosalvi03 approved these changes

2024-12-27 17:44 UTC, merged