UC modifica workflow
techminds-unipd/docs pull request #165
Opened 2024-12-23 21:44 UTC by cvallott

close #153
Cari verificatori, io ci ho provato speriamo sia giusto. Inizialmente avevo pensato di fare un use case per la modifica e poi due generalizzazioni: 'modifica workflow vuoto' e 'modifica workflow non vuoto' perchè effettivamente nel secondo caso c'è già un workflow. Poi però sono tornata indietro sui miei passi e ho deciso di fare un unico use case come potrete vedere. 

Se ritenete che la forma con cui ho scritto non sia corretta o se l'opzione migliore era con le generalizzazioni fatemi sapere che agisco di conseguenza.

(Ovviamente non guardate l'uc della creazione, ci penso io poi a mergiare quando una delle due PR viene approvata)

2024-12-24 09:35 UTC, MatteoSquarz requested changes

2024-12-24 09:35 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. può selezionare un nuovo blocco di automazione e trascinarlo all'interno dell'area drag and drop;
dire che "può" non so se sia corretto sinceramente, sembra un qualcosa che può accadere come no, dunque non possiamo dire che ogni punto di questa procedura venga effettuato...

2024-12-24 09:37 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. può selezionare un nuovo blocco di automazione e trascinarlo all'interno dell'area drag and drop;
infatti era il mio dubbio, ma come faccio a loro a dividere tra caso in cui in workflow è vuoto e in cui non è vuoto? tocca fare la generalizzazione?

2024-12-24 09:38 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. può selezionare un nuovo blocco di automazione e trascinarlo all'interno dell'area drag and drop;
perchè se poi modifico un workflow già creato magari voglio solo modificare gli archi e non i blocchi, quindi anche li dovrei usare il verbo 'può' perchè non sappiamo cosa vuole fare l'utente

2024-12-24 09:52 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. può selezionare un nuovo blocco di automazione e trascinarlo all'interno dell'area drag and drop;
si potrebbe scrivere in maniera diversa più simile a quello dell'UC del blocco gmail dove le funzionalità vengono elencate.
Del tipo l'utente sceglie tra le funzionalità offerte: aggiungere, togliere nodi e archi, e lo fa fino a quando non è soddisfatto del workflow che voleva ottenere

2024-12-24 09:53 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. può selezionare un nuovo blocco di automazione e trascinarlo all'interno dell'area drag and drop;
io non dividerei tra workflow vuoto e non vuoto mi sembra una cosa superflua, in ogni caso un workflow vuoto è pur sempre un workflow

2024-12-24 12:26 UTC, MatteoSquarz submitted a review, later dismissed
mi sembra più corretto ora, magari attendiamo pure il giudizio di @leosalvi03

2024-12-26 11:31 UTC, leosalvi03 requested changes

2024-12-26 11:31 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. sceglie tra le funzionalità di modifica offerte: aggiungere e togliere nodi di automazione e archi e modificare/aggiungere la descrizione dell'automazione in linguaggio naturale sugli archi;
Hai riflettuto sulla possibilità di modellare come estensioni o sottocasi queste funzionalità e sei giunta alla conclusione che non fosse possibile o non ci avevi pensato?

2024-12-26 11:31 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - L'utente ha creato un workflow.
Con creato intendi "creato vuoto o caricato un salvataggio" o solo creato vuoto? (Mi è venuto in mente che forse dovremmo creare un UC per il caricamento di un workflow salvato)

2024-12-26 12:06 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - L'utente ha creato un workflow.
intendo che sostanzialmente ha creato almeno un workflow da poter modificare (non mi interessa che sia vuoto o no, basta che in qualche momento l'abbia creato e lo voglia modificare)

2024-12-26 12:25 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. sceglie tra le funzionalità di modifica offerte: aggiungere e togliere nodi di automazione e archi e modificare/aggiungere la descrizione dell'automazione in linguaggio naturale sugli archi;
la domanda da porsi è sarebbe corretto che queste fossero estensioni? perchè di certo non sono include dato che non è detto che alcune operazioni debbano essere eseguite.

2024-12-26 13:26 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. sceglie tra le funzionalità di modifica offerte: aggiungere e togliere nodi di automazione e archi e modificare/aggiungere la descrizione dell'automazione in linguaggio naturale sugli archi;
secondo me non possono essere delle estensioni, al massimo generalizzazioni. però anche fatto così dovrebbe avere senso..credo

2024-12-26 15:38 UTC, cvallott commented
ho usato come presupposto che non si possa collegare un blocco con se stesso

2024-12-26 17:47 UTC, MatteoSquarz requested changes

2024-12-26 17:47 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +- *Descrizione*
Te lo scrivo solo qui ma mancano i ":" dopo Descrizione praticamente in tutti i nuovi use case che hai fatto

2024-12-26 17:47 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - I blocchi sono scollegati tra loro.
sottolinerei che i blocchi che voglio collegare sono scollegati tra loro, ma in generale non tutti i blocchi devono essere scollegati

2024-12-26 17:50 UTC, MatteoSquarz commented
Vedendolo cosi mi sembra più corretto rispetto a prima, sentiamo anche @leosalvi03 che ne pensa

2024-12-26 18:09 UTC, leosalvi03 requested changes
Ci sono tante domande. Se vuoi domani proviamo a dare una risposta assieme, così ti spiego meglio alcuni commenti che potrebbero non esserti chiari. Conta che li ho scritti abbastanza di getto per evitare di cadere in loop di pensieri troppo complessi

2024-12-26 18:09 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>  - *Descrizione*
```suggestion
- *Descrizione:*
```

2024-12-26 18:09 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +- *Descrizione*
```suggestion
- *Descrizione:*
```

2024-12-26 18:09 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +- *Descrizione*
```suggestion
- *Descrizione:*
```

2024-12-26 18:09 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +- *Descrizione*
```suggestion
- *Descrizione:*
```

2024-12-26 18:09 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - I blocchi sono collegati tra loro.
Quali blocchi e quanti? Tutti? Almeno due?

2024-12-26 18:09 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. collega i due blocchi prescelti attraverso un arco orientato.
Quando collego un arco devo per forza scrivere su esso in modo che non rimanga senza descrizione?

2024-12-26 18:09 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - Viene aggiunta la descrizione dell'automazione.
Quale automazione? Direi quella che l'utente seleziona

2024-12-26 18:09 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - Viene modificata la descrizione dell'automazione.
Quale automazione? Direi quella che l'utente seleziona

2024-12-26 18:09 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - Viene eliminato l'arco orientato tra i due blocchi.
Specificherei l'arco selezionato dall'utente

2024-12-26 18:09 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - Viene creato un arco orientato tra i due blocchi.
Specificherei selezionati dall'utente

2024-12-26 18:11 UTC, leosalvi03 commented
> Vedendolo cosi mi sembra più corretto rispetto a prima, sentiamo anche @leosalvi03 che ne pensa

Molto meglio, ho scritto però un po' di commenti su dei dubbi non proprio piccoli che mi sono venuti. Come ho detto a Caterina, magari domani ne parliamo

2024-12-26 19:24 UTC, MatteoSquarz commented
> Ci sono tante domande. Se vuoi domani proviamo a dare una risposta assieme, così ti spiego meglio alcuni commenti che potrebbero non esserti chiari. Conta che li ho scritti abbastanza di getto per evitare di cadere in loop di pensieri troppo complessi
Potrebbe essere la cosa migliore @cvallott

2024-12-26 19:27 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     1. seleziona il workflow da modificare;
si è la cosa migliore non può esserci sempre una nuova schermata per ogni piccola operazione da fare

2024-12-26 19:27 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   2. gestisce gli input dell'utente.
yes

2024-12-26 19:30 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. scollega i due blocchi prescelti eliminando l'arco orientato che li collegava.
qua descrive cosa vogliamo che succeda, quindi scollegare i due blocchi eliminando l'arco che li collega

2024-12-26 19:31 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. collega i due blocchi prescelti attraverso un arco orientato.
direi di no

2024-12-26 19:33 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - Viene aggiunta la descrizione dell'automazione.
si dico lo solo qua ma sono d'accordo visto che ci potrebbero essere tanti nodi, tanti archi e tante descrizioni forse è meglio specificare quello che l'utente seleziona.

2024-12-26 19:36 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. collega i due blocchi prescelti attraverso un arco orientato.
qui forse descrivi già come a noi basta dire il cosa, quindi dire che li collego attraverso un arco orientato mi sembra sufficiente

2024-12-27 12:09 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     1. porta l'utente nella pagina per la modifica dei workflow;
sono d'accordo, aggiorno anche l'UC della visualizzazione dei blocchi

2024-12-27 16:08 UTC, MatteoSquarz requested changes

2024-12-27 16:08 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Questo caso d'uso descrive la procedura di avvio di modifica di un workflow.
```suggestion
  - Questo caso d'uso descrive la procedura per entrare in modalità di modifica di un workflow.
```

2024-12-27 16:12 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   2. gestisce gli input dell'utente;
ogni volta diciamo "gli input" ma siamo sicuri che ora sia giusto usare il plurale?

2024-12-27 16:14 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   2. gestisce gli input dell'utente;
dato che ci stiamo riferendo ad una operazione singola (e se vuole farla più volte riparte da capo lo UC) forse è meglio mettere l'input e non gli input. @leosalvi03 dizionario vivente cosa ne pensi?

(in caso correggo tutto in una volta sola anche con le modifiche di leo)

2024-12-27 17:12 UTC, leosalvi03 requested changes
Ho posto ancora qualche domanda, ma mi sembra che siamo sulla strada giusta! Top number one GRANDI!!!!! @cvallott @MatteoSquarz

2024-12-27 17:12 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. gestisce gli input dell'utente;
Che sia il caso di specificare (come passaggio del sistema o come precondizione) i controlli sulla validità del collegamento (non collego un blocco con se stesso e posso avere al massimo un collegamento in entrata per ogni blocco)?
Non sono sicuro al 100% del secondo vincolo

2024-12-27 17:12 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - L'utente ha creato un workflow;
Per tutti gli UC a parte la modifica: queste precondizioni non sono già incluse nell'essere entrati in modalità modifica? Dato che sono precondizioni della modifica

2024-12-27 17:12 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +=== Aggiunta descrizione <aggiunta-descrizione>
@cvallott @MatteoSquarz Questo UC non è un include dell'aggiunta di un arco? Quando aggiungo un arco devo aggiungere per forza una descrizione. Poi in caso posso modificarla con l'UC separato. Non so se sia saggio dare la possibilità di creare workflows con archi che non hanno associata un'azione

2024-12-27 17:12 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   2. modifica la descrizione dell'automazione scelta indicando in linguaggio naturale la nuova descrizione.
```suggestion
   2. modifica la descrizione dell'automazione scelta indicando in linguaggio naturale la nuova azione che deve fare il sistema.
```

2024-12-27 17:12 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>   - Utente autenticato:
@cvallott @MatteoSquarz Non sono convinto ma pongo la domanda: può essere che questo sia un include dell'uc della modifica? Quando il sistema mostra la schermata di modifica mostra anche la lista dei blocchi configurati

2024-12-27 20:52 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +=== Modifica workflow <modifica-workflow>
si manca uno uc di visualizzazione pura del workflow, per quanto riguarda la possibilità di uscire dalla modalità di modifica potrebbe essere sensato

2024-12-27 20:53 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. aggiorna il workflow.
direi che è incluso nell'aggiorna

2024-12-27 20:54 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. gestisce gli input dell'utente;
Non necessario a mio parere

2024-12-27 20:55 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - L'utente ha creato un workflow;
effettivamente si, poi un pò di ridondanza di questo tipo non penso sia troppo dannosa rende più chiaro gli uc anche perchè non sono modellati in un unico diagramma

2024-12-27 20:56 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +=== Aggiunta descrizione <aggiunta-descrizione>
no non sono obbligato, come dicevamo l'utente può creare workflow sintatticamente non validi ma comunque essere in grado salvarli.

2024-12-27 20:57 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>   - Utente autenticato:
in realtà si potrebbe aver senso

2024-12-27 20:58 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +=== Modifica workflow <modifica-workflow>
non è detto però che dopo aver inserito un blocco l'utente abbia già finito, può essere che voglia fare altro. servirebbe quindi un uc specifico per uscire dalla modalità di modifica?

2024-12-27 21:00 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +=== Modifica workflow <modifica-workflow>
si esattamente

2024-12-27 21:04 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +=== Modifica workflow <modifica-workflow>
vera taglia di questa issue: XXXL
abbiamo sottovalutato la questione 

domani mattina mi rimetto a sistemare

2024-12-28 07:56 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   2. gestisce gli input dell'utente;
dopo un intensa riflessione, ho deciso di cambiare solo quelli in cui l'input dell'utente è solo uno (in alcuni casi c'è prima la selezione e poi un'altra azione, quindi siamo a due input)

2024-12-28 08:01 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - L'utente ha creato un workflow;
tolgo la ridondanza

2024-12-28 09:13 UTC, cvallott commented
Cari verificatori, ho aggiunto UC di uscita dalla modalità di modifica e provato a fare l'include dell'UC di visualizzazione dei blocchi. In quest'ultimo ci sono dei passaggi che non mi tornano molto (cosa fa l'utente nell'UC di estensione dell'inclusione? per ora ho lasciato 'avvia la procedura di modifica' perchè mettere 'visualizza i blocchi' non mi sembrava corretto dato che non li visualizza in realtà). Ho ancora abbastanza dubbi.

2024-12-28 09:38 UTC, MatteoSquarz requested changes

2024-12-28 09:38 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    1. avvia la procedura di modifica di un nuovo workflow.
si può mettere visualizza avviso servizi non collegati, la procedura di modifica la ha già avviata in teoria

2024-12-28 09:38 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     1. gestisce gli input dell'utente;
qui è rimasto gli input non so se sia voluto

2024-12-28 09:38 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     - Sopra almeno un arco di collegamento è presente una descrizione;
scritto male, meglio "è presente una descrizione in almeno un arco orientato del workflow"

2024-12-28 09:38 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +=== Uscita modalità modifica <stop-modifica-workflow>
uniformerei i nomi dei due uc che permettono di entrare/uscire dalla modalità di modifica

2024-12-28 09:38 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   2. seleziona l'opzione per salvare il workflow modificato (@salvataggio-workflow);
errore logico, quando esco dalla modalità di modifica nessuno mi obbliga a salvare, le cose sono slegate

2024-12-28 09:47 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   2. seleziona l'opzione per salvare il workflow modificato (@salvataggio-workflow);
allora tolgo proprio il riferimento al salvataggio da questo UC?

2024-12-28 09:48 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
>     1. gestisce gli input dell'utente;
si, lascio al plurale quando l'utente fa più di una cosa, al singolare quando ne fa solo una

2024-12-28 09:50 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    1. avvia la procedura di modifica di un nuovo workflow.
non lo so, non mi torna. penso che su utente dovremmo scrivere l'azione che fa, il fatto che visualizza l'avviso servizi non collegati è il risultato dell'UC..non so se mi sono spiegata

2024-12-28 10:13 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    1. avvia la procedura di modifica di un nuovo workflow.
@leosalvi03 tu che ne pensi

2024-12-28 10:14 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   2. seleziona l'opzione per salvare il workflow modificato (@salvataggio-workflow);
si il salvataggio non c'entra nulla con questo uc

2024-12-29 11:34 UTC, cvallott commented
ed eccoci di nuovo qui, allora ho sistemato un pochino l'UC di entrata in modalità modifica. In sintesi il problema era che le precondizioni dell'attuale UC15 era che l'utente aveva associato almeno un servizio, ma in questo modo l'UC16 (estensione) non si verificava mai. Quindi ho spostato la condizione dell'associazione sull'UC15.1 (infatti l'associazione deve essere fatta altrimenti non visualizza i blocchi) e sull'UC16 ho messo che invece l'utente non ha collegato nessun servizio. 

Così mi torna di più. Fatemi sapere cosa ne pensate. (Tutti gli altri UC dovrebbe comunque tornare perchè le precondizioni sono comunque rimaste quelle ma le ho posizionate in posti diversi)

2024-12-29 15:24 UTC, leosalvi03 requested changes
Qualche piccolo appunto ma davvero un ottimo lavoro nel complesso. Complimenti!

2024-12-29 15:24 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   4. visualizza i blocchi disponibili (@visualizzazione-blocchi-configurati).
Aggiungerei che visualizza anche il workflow

2024-12-29 15:24 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - L'utente ha creato un workflow.
Creato o memorizzato nell'applicazione? Potrei aver creato e distrutto un solo workflow, quindi non averne memorizzato nessuno

2024-12-29 15:24 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    1. visualizza avviso servizi non collegati.
```suggestion
    1. Visualizza un avviso che segnala l'assenza di servizi collegati.
```

2024-12-29 15:24 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. gestisce l'input dell'utente;
É troppo/superfluo specificare che il sistema controlla l'idoneità del collegamento e mettere come estensione la segnalazione dell'eventuale inidoneità?

2024-12-29 15:24 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - Viene eliminato l'arco orientato tra i due blocchi selezionato dall'utente.
```suggestion
   - Viene eliminato l'arco orientato tra i due blocchi selezionati dall'utente.
```
Errore di battitura

2024-12-29 15:24 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - Il workflow ha almeno due blocchi collegati tra loro;
```suggestion
   - Il workflow ha almeno due blocchi collegati tramite un arco che non specifica alcuna descrizione;
```
Specificherei che aggiungo a un arco vuoto per non confonderlo con la modifica

2024-12-29 15:24 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. seleziona l'opzione per uscire dalla modalità di modifica.
```suggestion
   2. seleziona l'opzione per uscire dalla modalità di modifica.
```
Numerazione da correggere

2024-12-29 15:24 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. mostra la schermata con tutti i workflow.
```suggestion
   1. esce dalla modalità di modifica;
   2. mostra la schermata con tutti i workflow.
```
Numerazione da correggere

2024-12-29 15:26 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   4. visualizza i blocchi disponibili (@visualizzazione-blocchi-configurati).
non è scritto nel punto 2?

2024-12-29 15:27 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - L'utente ha creato un workflow.
dici di scrivere 'ha creato e salvato'?

2024-12-29 15:29 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. gestisce l'input dell'utente;
in che casi non è idoneo? nelle precondizioni abbiamo messo che i due blocchi scelti non sono collegati quindi in teoria dovremmo essere 'coperti' da eventuali errori compiuti dall'utente

2024-12-29 15:33 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. gestisce l'input dell'utente;
Ad esempio non posso avere più di un arco entrante (da quel che ricordo, per sicurezza forse bisognerebbe chiedere a Giuseppe), non posso connettere un blocco con sé stesso. In ogni caso anche se un utente tenta di connettere due blocchi già collegati bisogna segnalare l'errore.

2024-12-29 15:35 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. gestisce l'input dell'utente;
confermo, a mio parere siamo apposto cosi

2024-12-29 15:37 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. gestisce l'input dell'utente;
ma l'utente non potrà proprio mettere un arco in un blocco che è già collegato credo. comunque mettere un caso di estensione in cui si verifica una situazione del genere non ha senso perchè nelle pre-condizioni diciamo che deve scegliere due blocchi non collegati. al massimo dovrà essre un nuovo UC (?) ma credo ci si possa pensare in futuro

2024-12-29 15:37 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   4. visualizza i blocchi disponibili (@visualizzazione-blocchi-configurati).
Sì ma io specificherei che quando seleziono l'opzione di modifica visualizzo sia i blocchi disponibili che il workflow (e non solo la schermata dei blocchi disponibili). Oppure metterei "Visualizza **anche** i blocchi disponibili"

2024-12-29 15:38 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - L'utente ha creato un workflow.
Non è detto che lo abbia salvato però. Magari non è ancora "persistente"

2024-12-29 15:39 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   4. visualizza i blocchi disponibili (@visualizzazione-blocchi-configurati).
ahnn ok ora ho capito cosa intendi, scusa prima non avevo compreso. si sono d'accordo con te

2024-12-29 15:52 UTC, leosalvi03 approved these changes

2024-12-29 17:15 UTC, MatteoSquarz requested changes

2024-12-29 17:15 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    1. mostra i blocchi che hanno un servizio associato nella sezione dei blocchi configurati.
```suggestion
    2. mostra i blocchi che hanno un servizio associato nella sezione dei blocchi configurati.
```

2024-12-29 17:15 UTC, MatteoSquarz commented
bel lavoro!

2024-12-29 17:19 UTC, MatteoSquarz approved these changes

2024-12-29 17:23 UTC, merged