UC approfondimento - backend
techminds-unipd/docs pull request #168
Opened 2024-12-27 14:37 UTC by cvallott

close #167 

Cari verificatori, io e @T-Brex abbiamo suddiviso la issue di approfondimento in due issue (una è questa). In particolare in questi UC vado a descrivere il punto di vista del back-end che si interfaccia con l'agente. (ale farà quello in cui front-end si interfaccia con tutto il sistema ad eccezione di lui stesso ovviamente).

Per Leo spiego il ragionamento che è stato fatto con i programmatori:
- sistema formato da: front-end, back-end, agente e database
- in questo UC praticamente abbiamo approfondito il back-end che si interfaccia con l'agente durante l'esecuzione del workflow (senza andare troppo nel dettaglio perchè comunque resta una cosa ad alto livello)
- l'errore di time-out che vedete in parole povere è quando l'agente e l'LLM vanno in loop, ci sarà quindi un tempo massimo che permette di uscire da tale condizione

Lascio a voi l'aggiunta della riga del changelog

2024-12-27 16:20 UTC, MatteoSquarz requested changes
Sostanzialmente corretto dal mio punto di vista, non viene spiegato nel dettaglio le interazioni dell'agente con LLM esterno ma penso sia voluto

2024-12-27 16:20 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   2. inizia ad eseguire le automazioni interfacciandosi con un LLM esterno;
sbagliato dire inizia ad eseguire meglio dire semplicemente "esegue" (happy path)

2024-12-27 16:20 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Back-end.
back-end va con il tratttino ? domanda stupida

2024-12-27 16:20 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Questo caso d'uso descrive le operazioni di esecuzione del back-end durande la procedura di esecuzione di un workflow.
non viene menzionato l'agente.. anche lui compie delle operazioni

2024-12-27 16:23 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Back-end.
In [software engineering](https://en.wikipedia.org/wiki/Software_engineering), the terms frontend and backend (sometimes written as back end or back-end) refer to the [separation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns) between the [presentation layer](https://en.wikipedia.org/wiki/Presentation_layer) (frontend), and the [data access layer](https://en.wikipedia.org/wiki/Data_access_layer) (backend) of a piece of [software](https://en.wikipedia.org/wiki/Software), or the physical infrastructure or [hardware](https://en.wikipedia.org/wiki/Hardware_(computer))
fonte wikipedia

2024-12-27 17:28 UTC, leosalvi03 requested changes
Bel lavoro! Grazie anche per la spiegazione nella descrizione della pr

2024-12-27 17:28 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +=== Approfondimento esecuzione workflow back-end <esecuzione-workflow-backend>
Io darei un nome più esplicativo. Ad esempio: Esecuzione del workflow da parte dell'agente. Volendo puoi citare che è un UC di approfondimento; specificherei anche approfondimento di quale altro UC

2024-12-27 17:28 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Questo caso d'uso descrive le operazioni di esecuzione del back-end durande la procedura di esecuzione di un workflow.
Appunto. Qui dici che descrive le operazioni di esecuzione del backend, che però è l'attore e non il sistema. Non mi è chiaro cosa intendi

2024-12-28 07:42 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Back-end.
quindi come lo volete?

2024-12-28 09:19 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Back-end.
penso che sia meglio backend

2024-12-28 09:20 UTC, MatteoSquarz requested changes

2024-12-28 09:20 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Questo caso d'uso descrive le operazioni di esecuzione del back-end e dell'agente durante la procedura di esecuzione di un workflow, approfondendo @esecuzione-workflow.
cambiare back-end in backend dappertutto

2024-12-28 09:21 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Questo caso d'uso descrive le operazioni di esecuzione del back-end e dell'agente durante la procedura di esecuzione di un workflow, approfondendo @esecuzione-workflow.
ai suoi ordini

2024-12-28 10:17 UTC, MatteoSquarz requested changes

2024-12-28 10:17 UTC, MatteoSquarz commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +=== Esecuzione del workflow da parte dell'agente. <esecuzione-workflow-agente>
```suggestion
=== Esecuzione del workflow da parte dell'agente <esecuzione-workflow-agente>
```
senza il punto finale

2024-12-28 13:24 UTC, MatteoSquarz approved these changes

2024-12-29 15:36 UTC, leosalvi03 requested changes
Due errori sulla punteggiatura degli elenchi. Contenuto buono!

2024-12-29 15:36 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. invia i dati necessari per l'esecuzione del workflow all'agente;
```suggestion
   1. invia i dati necessari per l'esecuzione del workflow all'agente.
```
Ultima voce elenco termina con .

2024-12-29 15:36 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. invia i dati necessari per l'esecuzione del workflow all'agente;
```suggestion
   1. invia i dati necessari per l'esecuzione del workflow all'agente.
```
Ultima voce di un elenco termina con .

2024-12-29 15:53 UTC, leosalvi03 approved these changes

2024-12-29 16:01 UTC, merged