Processi primari sviluppo
techminds-unipd/docs pull request #169
Opened 2024-12-28 08:43 UTC by Jacky8703

Sezione 2.2, alcune parti non le ho scritte perché ritengo vadano messe più avanti, e ho scritto dei commenti nel codice per non sporcare il documento. close #157

2024-12-28 10:11 UTC, MatteoSquarz requested changes

2024-12-28 10:11 UTC, MatteoSquarz commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +- Scenario principale: sequenza di azioni che descrive il comportamento dell'attore e del sistema nel caso in cui non si verifichino errori;
toglierei nel caso non si verifichino errori, lo scenario principale è di tutti gli uc anche quelli di errore

2024-12-28 10:11 UTC, MatteoSquarz commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +- Sistema: rappresenta il "dominio" di un particolare caso caso d'uso, serve a stabilire il confine tra ciò che è esterno e quindi non gestito dal sistema e ciò che invece è interno e quindi gestito
scritto due volte caso

2024-12-28 10:11 UTC, MatteoSquarz commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +    - inclusione: relazione tra due casi d'uso, indica che un caso d'uso ne include un altro, può essere una funzionalità comune a più casi d'uso. Ogni istanza del caso d'uso "includente" esegue semp
"includente" lo hai letto da qualche parte o te lo sei inventato?

2024-12-28 10:11 UTC, MatteoSquarz commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +- "M", mandatory, requisito obbligatorio, irrinunciabile per qualcuno degli #glossario[stakeholder];
nel pdf non vedo il ; alla fine di questa frase

2024-12-28 10:11 UTC, MatteoSquarz commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +2. Descrizione, una breve descrizione del requisito;
per questo elenco non hai usato i : che forse erano meglio delle ,

2024-12-28 10:12 UTC, MatteoSquarz commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +2. Descrizione, una breve descrizione del requisito;
intendo nei punti 1 2 e 3

2024-12-28 13:18 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +#align(center)[UC.a.b Nome]dove "a" è il numero del caso d'uso, "b" è il numero del sotto caso d'uso, se presente, e "Nome" è il nome del caso d'uso (esplicativo del suo scopo);
il documento si basa su ciò che facciamo noi, secondo me è da cambiare solo se succede che in un nostro UC andiamo un livello ancora sotto

2024-12-28 13:20 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +In generale l'analisi descrive la struttura funzionale del prodotto, quindi cosa deve succedere, e un modo per farlo è attraverso la scrittura dei casi d'uso.
slide 4 pdf big T analisi dei requisiti, se vuoi cambio lo stesso idc

2024-12-28 13:21 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +- Scenario principale: sequenza di azioni che descrive il comportamento dell'attore e del sistema nel caso in cui non si verifichino errori;
true, stavo pensando all'happy path

2024-12-28 13:23 UTC, MatteoSquarz commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +In generale l'analisi descrive la struttura funzionale del prodotto, quindi cosa deve succedere, e un modo per farlo è attraverso la scrittura dei casi d'uso.
@leosalvi03 scegli tu se tenere la frase di @Jacky8703 oppure se mettere il mio suggerimento

2024-12-28 13:23 UTC, MatteoSquarz commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +#align(center)[UC.a.b Nome]dove "a" è il numero del caso d'uso, "b" è il numero del sotto caso d'uso, se presente, e "Nome" è il nome del caso d'uso (esplicativo del suo scopo);
ok approvo, speriamo di mantenere questa forma allora

2024-12-28 13:25 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +    - inclusione: relazione tra due casi d'uso, indica che un caso d'uso ne include un altro, può essere una funzionalità comune a più casi d'uso. Ogni istanza del caso d'uso "includente" esegue semp
participio passato includere, dovrebbe essere giusto il senso "che include"

2024-12-28 13:26 UTC, MatteoSquarz commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +    - inclusione: relazione tra due casi d'uso, indica che un caso d'uso ne include un altro, può essere una funzionalità comune a più casi d'uso. Ogni istanza del caso d'uso "includente" esegue semp
ok suona un pò male il tutto secondo me, meglio mettere "che include" se proprio

2024-12-28 13:29 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +2. Descrizione, una breve descrizione del requisito;
intendi dopo Codice identificativo univoco, Descrizione e Fonti?

2024-12-28 13:42 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +    - inclusione: relazione tra due casi d'uso, indica che un caso d'uso ne include un altro, può essere una funzionalità comune a più casi d'uso. Ogni istanza del caso d'uso "includente" esegue semp
ci saranno delle ripetizioni ma amen

2024-12-29 17:25 UTC, leosalvi03 requested changes
Ho corretto delle piccolezze. Hai fatto un buon lavoro

2024-12-29 17:25 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +In generale l'analisi descrive la struttura funzionale del prodotto, quindi cosa deve succedere, e un modo per farlo è attraverso la scrittura dei casi d'uso.
```suggestion
In generale, l'analisi studia a fondo i bisogni, con particolare attenzione al "cosa" deve succedere nel prodotto che verrà sviluppato, ovvero alla sua struttura funzionale. I requisiti riflettono la prospettiva dell'utente nel passaggio dalla situazione senza a quella con il prodotto. Uno dei modi più efficaci per individuare i requisiti è attraverso la scrittura dei casi d'uso.
```
@Jacky8703 @MatteoSquarz vi propongo questa modifica, frutto dell'unione del meglio di entrambe le versioni (mi piacevano entrambe)

2024-12-29 17:25 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +#figure(
Da NdP ogni figura dovrebbe avere la didascalia. Non metterla è stata una scelta?

2024-12-29 17:25 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +    - estensione: relazione tra due casi d'uso, indica che un caso d'uso può estenderne un altro (aumenta le funzionalità), o anche più casi d'uso diversi. Ogni istanza del caso d'uso "base" esegue i
```suggestion
    - estensione: relazione tra due casi d'uso, indica che un caso d'uso può estendere uno o più casi d'uso, aumentandone le funzionalità. Ogni istanza del caso d'uso "base" esegue il caso d'uso che estende in modo condizionato (a differenza dell'inclusione) e questo dipende dalla condizione di estensione, la quale determina quando l'estensione deve essere utilizzata. Con le estensioni si vogliono descrivere variazioni dalla funzionalità del caso d'uso "base", ad esempio in caso di errore/eccezione;
```

2024-12-29 17:25 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +- "O", optional, requisito opzionale, relativamente utile o contrattabile più avanti nel progetto;
```suggestion
- "O", optional, requisito opzionale, relativamente utile e contrattabile anche quando il progetto è in uno stato avanzato;
```
Per non far riferimento all'istante in cui è stato scritto il documeto

2024-12-29 17:25 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +"N" è un numero progressivo (es. QMR 2 indica un requisito di qualità obbligatorio numero 2);
Farei rientrare un pochino a destra queste righe in modo da facilitare la lettura dell'elenco evidenziando la gerarchia tra le parti

2024-12-29 17:25 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +A supporto dell'attività di progettazione verranno utilizzati i diagrammi delle classi, vista la loro utilità nel documentare in modo conciso l'architettura e nella futura fase di implementazione.
```suggestion
A supporto dell'attività di progettazione verranno utilizzati i diagrammi delle classi, vista la loro utilità nel documentare in modo conciso l'architettura nella futura fase di implementazione.
```

2024-12-29 17:25 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +- Aiutano ad identificare le responsabilità delle singole classi e a definire chiaramente i confini tra di esse;
```suggestion
- Aiutano a identificare le responsabilità delle singole classi e a definire chiaramente i confini tra di esse;
```
La d va messa solo se la parola successiva inizia per a

2024-12-29 17:25 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +- Consentono di individuare potenziali problemi di progettazione, prima di iniziare la fase di codifica, riducendo così di molto il costo di modifiche o future correzioni;
```suggestion
- Consentono di individuare potenziali problemi di progettazione prima di iniziare la fase di codifica, riducendo così di molto il costo di modifiche o future correzioni;
```

2024-12-29 17:25 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +L'attività di codifica e testing consiste nella realizzazione effettiva del prodotto software. Durante questa fase il codice viene scritto e testato per garantire che il prodotto soddisfi i requisiti
```suggestion
L'attività di codifica e testing consiste nella realizzazione effettiva del prodotto software. Durante questa fase, il codice viene scritto e testato per garantire che il prodotto soddisfi i requisiti individuati in fase di analisi e rispetti la progettazione definita al passo precedente. L'obiettivo è quello di creare il prodotto software richiesto dal committente, rispettando gli accordi stipulati in fase di fornitura.
```

2024-12-29 17:25 UTC, leosalvi03 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +L'attività di integrazione consiste nell'unione delle parti di software sviluppate in precedenza, per formare un'unica entità funzionante. Ad ogni nuovo sviluppo corrisponde una nuova integrazione in
```suggestion
L'attività di integrazione consiste nell'unione delle parti di software sviluppate in precedenza, per formare un'unica entità funzionante. A ogni nuovo sviluppo corrisponde una nuova integrazione, in modo tale da verificare il prima possibile che l'elemento appena integrato sia conforme alle aspettative. L'obiettivo è quello di verificare che le singole parti del software funzionino correttamente nel loro insieme.
```

2024-12-29 17:28 UTC, MatteoSquarz commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +In generale l'analisi descrive la struttura funzionale del prodotto, quindi cosa deve succedere, e un modo per farlo è attraverso la scrittura dei casi d'uso.
mi piace

2024-12-30 09:42 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +- Aiutano ad identificare le responsabilità delle singole classi e a definire chiaramente i confini tra di esse;
the more you know

2024-12-30 09:51 UTC, Jacky8703 commented on RTB/documenti_interni/norme_progetto/include/processi-primari.typ
> +#figure(
si mi sembrava una ripetizione inutile nelle relazioni, se dici la metto comunque

2024-12-31 09:10 UTC, leosalvi03 approved these changes

2024-12-31 13:28 UTC, MatteoSquarz approved these changes

2024-12-31 13:34 UTC, merged