Aggiunta consuntivo sprint 2 e diagramma di Gantt
techminds-unipd/docs pull request #170
Opened 2024-12-28 16:09 UTC by T-Brex

close #156

2024-12-28 20:28 UTC, MatteoSquarz requested changes

2024-12-28 20:28 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/costi.typ
>      for i in range(0, sprint_number) {
@Giuseppe5000 in questo ciclo ce una bella sottolineatura rossa a riga 46, leggendo il codice mi sembra che la cosa si possa risolvere mettendo a riga 44 sprint_number - 1

2024-12-28 20:28 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint2.typ
> +    [Per una maggiore leggibilità dei task è stato deciso di cambiare vari campi che andavano a descrivere una issue di github #list(
```suggestion
    [Per una maggiore leggibilità dei task è stato deciso di cambiare vari campi che andavano a descrivere una issue di github: #list(
```

2024-12-28 20:28 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint2.typ
> +    proprio, dando comunque priorità al ruolo deciso nello sprint planning;],
```suggestion
    proprio, dando comunque priorità al ruolo deciso nello sprint planning.],
```

2024-12-28 20:46 UTC, Giuseppe5000 commented on RTB/documenti_esterni/piano_progetto/include/costi.typ
>      for i in range(0, sprint_number) {
Ma che problema ti indica la sottolineatura rossa?

2024-12-28 20:47 UTC, Giuseppe5000 commented on RTB/documenti_esterni/piano_progetto/include/costi.typ
>      for i in range(0, sprint_number) {
Tecnicamente funziona così, se metto sprint_number -1 non conterei il penultimo sprint nel totale

2024-12-28 21:10 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/costi.typ
>      for i in range(0, sprint_number) {
> Ma che problema ti indica la sottolineatura rossa?

index out of range

2024-12-28 21:11 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/costi.typ
>      for i in range(0, sprint_number) {
se io passo sprint 2, sprint_number = 2, ma io ho solo due elementi non 3 quindi gli elementi sono con indice 0 e 1 non anche 2

2024-12-28 21:13 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/costi.typ
>      for i in range(0, sprint_number) {
magari è il mio vscode pazzo non lo so

2024-12-28 21:15 UTC, Giuseppe5000 commented on RTB/documenti_esterni/piano_progetto/include/costi.typ
>      for i in range(0, sprint_number) {
In range il secondo elemento non è compreso, indica il past the end. Quindi se passo 2 farà 0 e 1

2024-12-28 21:16 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/costi.typ
>      for i in range(0, sprint_number) {
ah perfetto allora tutto apposto

2024-12-29 10:45 UTC, MatteoSquarz requested changes

2024-12-29 10:45 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint2.typ
> +        [abbiamo deciso di cambiare i valori che rappresentavano il campo "Priority" dai valori "P0","P1" e "P2"  in "Alta", "Media" e "Bassa";],
```suggestion
        [abbiamo deciso di cambiare i valori che rappresentavano il campo "Priority" dai valori "P0","P1" e "P2"  in "Alta", "Media" e "Bassa".],
```

2024-12-29 10:45 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint2.typ
> +    [talvolta alcuni ruoli possono essere più scarni di lavoro di altri, abbiamo quindi deciso che i componenti del gruppo possono dedicare una parte delle proprie ore lavoro nel contribuire ad un ru
```suggestion
    [Talvolta alcuni ruoli possono essere più scarni di lavoro di altri, abbiamo quindi deciso che i componenti del gruppo possono dedicare una parte delle proprie ore lavoro nel contribuire ad un ruolo che non è il
```

2024-12-29 10:45 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint2.typ
> +    proprio, dando comunque priorità al ruolo deciso nello sprint planning;],
```suggestion
    proprio, dando comunque priorità al ruolo deciso nello sprint planning.],
```

2024-12-29 10:46 UTC, MatteoSquarz commented
o fai i 3 commit che ti ho suggerito sennò devi correggerli tu a mano e poi fare commit come al solito.

2024-12-29 11:17 UTC, MatteoSquarz approved these changes

2024-12-29 11:18 UTC, MatteoSquarz approved these changes

2024-12-29 16:35 UTC, leosalvi03 requested changes

2024-12-29 16:35 UTC, leosalvi03 commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint2.typ
> +        task("Redigere 'Pianificazione' in piano di progetto", (from: 5, to: 10, style: (stroke: 8pt + gray)), (from: 5, to: 10, style: (stroke: 2pt + red)))
É un errore che nel gruppo "Piano di qualifica" ci sa questa task del piano di progetto?

2024-12-29 16:35 UTC, leosalvi03 commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint2.typ
> +        task("Inizio implementazione agenti nel backend(non completata)", (from: 4, to: 10, style: (stroke: 8pt + gray)), (from: 5, to: 10, style: (stroke: 2pt + red)))
```suggestion
        task("Inizio implementazione agenti nel backend (non completata)", (from: 4, to: 10, style: (stroke: 8pt + gray)), (from: 5, to: 10, style: (stroke: 2pt + red)))
```
Aggiungerei uno spazio prima della parentesi

2024-12-29 16:35 UTC, leosalvi03 commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint2.typ
> +    [Talvolta alcuni ruoli possono essere più scarni di lavoro di altri, abbiamo quindi deciso che i componenti del gruppo possono dedicare una parte delle proprie ore lavoro nel contribuire ad un ru
```suggestion
    [Talvolta alcuni ruoli possono essere più scarni di lavoro di altri, abbiamo quindi deciso che i componenti del gruppo possono dedicare una parte delle proprie ore lavoro a contribuire ad un ruolo che non è il
```
La forma corretta è contribuire a, non contribuire in

2024-12-29 16:45 UTC, T-Brex commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint2.typ
> +        task("Redigere 'Pianificazione' in piano di progetto", (from: 5, to: 10, style: (stroke: 8pt + gray)), (from: 5, to: 10, style: (stroke: 2pt + red)))
Secondo me è scorretto, io l'ho lasciato così per come erano suddivise le issue nella pianificazione dello sprint 2, però avrebbe senso che sia nel gruppo "piano di progetto".
Se cambio nel gantt però devo cambiare anche il gruppo in cui si trova "Redigere 'Pianificazione' in piano di progetto" nella lista delle issue!

2024-12-29 17:05 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint2.typ
> +        task("Redigere 'Pianificazione' in piano di progetto", (from: 5, to: 10, style: (stroke: 8pt + gray)), (from: 5, to: 10, style: (stroke: 2pt + red)))
non ci avevi fatto caso ma va spostato assolutamente da entrambe le parti

2024-12-29 17:30 UTC, MatteoSquarz commented
Per questioni di coerenza farei il merge prima di questa pr piuttosto che l'altra che riguarda il pdp @leosalvi03

2024-12-29 18:34 UTC, leosalvi03 approved these changes

2024-12-29 18:39 UTC, merged