aggiunta preventivo sprint 3
techminds-unipd/docs pull request #171
Opened 2024-12-28 16:42 UTC by T-Brex

2024-12-28 20:10 UTC, MatteoSquarz requested changes

2024-12-28 20:10 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint3.typ
> +=== Sprint 3
questo sprint non è visibile nel piano di progetto, è necessario fare #include "sprint/sprint3.typ" nel file periodi.typ

2024-12-28 21:13 UTC, T-Brex commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint3.typ
> +=== Sprint 3
ops, non lo sapevo thanks

2024-12-28 21:59 UTC, MatteoSquarz approved these changes

2024-12-29 16:52 UTC, leosalvi03 requested changes

2024-12-29 16:52 UTC, leosalvi03 commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint3.typ
> +    - Analisi dei requisiti
```suggestion
    - Analisi dei Requisiti
```
Mi sono accorto che in questo elenco abbiamo messo ogni tanto le minuscole e ogni tanto le maiuscole per i nomi dei documenti (non parlo delle iniziali che sono già sempre maiuscole, giustamente). Successivamente ti segnalo anche le altre righe con questo tipo di errore. Potresti cambiare anche il corrispondente elenco nel preventivo dello sprint 2? Grazie, non me ne ero accorto in precedenza

2024-12-29 16:52 UTC, leosalvi03 commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint3.typ
> +        - #link("https://github.com/techminds-unipd/PoC/issues/8")[Issue \#8]: Gestione collegamento servizi Google;
```suggestion
        - #link("https://github.com/techminds-unipd/PoC/issues/8")[Issue \#8]: Gestione collegamento servizi Google.
```
Elenco termina con .

2024-12-29 16:52 UTC, leosalvi03 commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint3.typ
> +        - #link("https://github.com/techminds-unipd/docs/issues/154")[Issue \#154]: fix UC Visualizzazione blocchi configurati e avviso servizi collegati;
```suggestion
        - #link("https://github.com/techminds-unipd/docs/issues/154")[Issue \#154]: Fix UC Visualizzazione blocchi configurati e avviso servizi collegati.
```
Elenco termina con .

2024-12-29 16:52 UTC, leosalvi03 commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint3.typ
> +    - Norme di progetto
```suggestion
    - Norme di Progetto
```

2024-12-29 16:52 UTC, leosalvi03 commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint3.typ
> +        - #link("https://github.com/techminds-unipd/docs/issues/111")[Issue \#111]: Redigere nuove sezioni piano di qualifica (non completata durante lo sprint 2);
```suggestion
        - #link("https://github.com/techminds-unipd/docs/issues/111")[Issue \#111]: Redigere nuove sezioni piano di qualifica (non completata durante lo sprint 2).
```

2024-12-29 16:52 UTC, leosalvi03 commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint3.typ
> +        - #link("https://github.com/techminds-unipd/docs/issues/156")[Issue \#156]: Consuntivo sprint 2;
```suggestion
        - #link("https://github.com/techminds-unipd/docs/issues/156")[Issue \#156]: Consuntivo sprint 2.
```

2024-12-29 16:52 UTC, leosalvi03 commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint3.typ
> +       - #link("https://github.com/techminds-unipd/docs/issues/159")[Issue \#159]: aggiornamento ndp;
```suggestion
       - #link("https://github.com/techminds-unipd/docs/issues/159")[Issue \#159]: aggiornamento ndp.
```

2024-12-29 17:28 UTC, T-Brex commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint3.typ
> +    - Analisi dei requisiti
C'è qualche convenzione che abbiamo scelto? è meglio Analisi dei requisiti o Analisi dei Requisiti?

2024-12-29 18:42 UTC, leosalvi03 requested changes
Ho solo risposto al tuo commento

2024-12-29 18:42 UTC, leosalvi03 commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint3.typ
> +    - Analisi dei requisiti
Secondo me non avevamo scelto nulla. Guardando la copertina dei documenti io terrei solo l'iniziale maiuscola (quindi Analisi dei requisiti) @T-Brex

2024-12-29 19:17 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint3.typ
> +    - Analisi dei requisiti
io la terrei minuscola

2024-12-30 18:06 UTC, T-Brex commented on RTB/documenti_esterni/piano_progetto/include/sprint/sprint3.typ
> +    - Analisi dei requisiti
anch'io sono del parere di @MatteoSquarz

2025-01-02 10:50 UTC, leosalvi03 approved these changes

2025-01-02 11:05 UTC, merged