Aggiornare il template html e css
techminds-unipd/docs pull request #39
Opened 2024-11-08 13:58 UTC by T-Brex

close #34 
- cambio colore arancione
- cambio colore link visitato #800080
- aggiunta sezione RTB

2024-11-08 14:13 UTC, Giuseppe5000 commented
Non sono fra i verificatori, però direi che la sezione RTB dovrebbe essere sopra candidatura

2024-11-08 14:27 UTC, MatteoSquarz commented
Va bene ma invertite Candidatura e RTB, si devono vedere sempre le cose più recenti per ultime.

2024-11-08 14:28 UTC, MatteoSquarz requested changes
Va bene ma invertite Candidatura e RTB, si devono vedere sempre le cose più recenti per ultime.

2024-11-09 14:51 UTC, MatteoSquarz approved these changes

2024-11-09 14:51 UTC, Giuseppe5000 approved these changes

2024-11-09 14:51 UTC, merged