Verbale 15 11
techminds-unipd/docs pull request #63
Opened 2024-11-16 17:04 UTC by MatteoSquarz

2024-11-17 09:16 UTC, cvallott requested changes

2024-11-17 09:16 UTC, cvallott commented on RTB/documenti_esterni/verbali/2024-11-15.typ
> +  sommario: "Primo allineamento con l'azienda",
aggiungere il punto alla fine della frase

2024-11-17 09:16 UTC, cvallott commented on RTB/documenti_esterni/verbali/2024-11-15.typ
> +    "1.0.0", "15/11/2024", "Prima versione", team.M, "..."
la versione non era 0.1.0? almeno così l'avevamo messa sui documenti redatti nelle scorse issue. non so se per i verbali volevate gestirle in modo differente. chiedo per ignoranza

2024-11-17 09:16 UTC, cvallott commented on RTB/documenti_esterni/verbali/2024-11-15.typ
> +  partecipanti: (team.T, team.L, team.M, team.C, team.G, team.A),
guardando gli scorsi verbali esterni sarebbe da aggiungere anche i due partecipanti di var group

2024-11-18 07:07 UTC, cvallott approved these changes

2024-11-18 08:36 UTC, T-Brex requested changes

2024-11-18 08:36 UTC, T-Brex commented on RTB/documenti_esterni/verbali/2024-11-15.typ
> +  ordine_giorno: ("Discussione sulla modalità degli sprint", "Definizione primo sprint", "Prima discussione sulle tecnologie utilizzabili"),
Le lista "Ordine_giorno" dovrebbe avere i ";" e "." dove necessario.
Le altre liste ne hanno bisogno? (Durata e luogo, Partecipanti e Decisioni prese)

2024-11-18 08:41 UTC, cvallott commented on RTB/documenti_esterni/verbali/2024-11-15.typ
> +  ordine_giorno: ("Discussione sulla modalità degli sprint", "Definizione primo sprint", "Prima discussione sulle tecnologie utilizzabili"),
avevo notato anche io questa cosa, negli altri verbali non li abbiamo mai messi. a questo punto ne discutiamo oggi?

2024-11-18 08:48 UTC, T-Brex commented on RTB/documenti_esterni/verbali/2024-11-15.typ
> +  ordine_giorno: ("Discussione sulla modalità degli sprint", "Definizione primo sprint", "Prima discussione sulle tecnologie utilizzabili"),
Sono d'accordo con te @MatteoSquarz , ho voluto nominare le altre liste per sottoporre la questione ad una discussione collettiva

2024-11-18 08:49 UTC, MatteoSquarz commented on RTB/documenti_esterni/verbali/2024-11-15.typ
> +  ordine_giorno: ("Discussione sulla modalità degli sprint", "Definizione primo sprint", "Prima discussione sulle tecnologie utilizzabili"),
mi serve per mandarlo all'azienda ora

2024-11-18 08:49 UTC, MatteoSquarz commented on RTB/documenti_esterni/verbali/2024-11-15.typ
> +  ordine_giorno: ("Discussione sulla modalità degli sprint", "Definizione primo sprint", "Prima discussione sulle tecnologie utilizzabili"),
io lascerei cosi al momento

2024-11-18 08:50 UTC, cvallott commented on RTB/documenti_esterni/verbali/2024-11-15.typ
> +  ordine_giorno: ("Discussione sulla modalità degli sprint", "Definizione primo sprint", "Prima discussione sulle tecnologie utilizzabili"),
se decidiamo di farlo così lo facciamo per tutti dato che devono firmarlo e non si può più cambiare

2024-11-18 08:52 UTC, MatteoSquarz commented on RTB/documenti_esterni/verbali/2024-11-15.typ
> +  ordine_giorno: ("Discussione sulla modalità degli sprint", "Definizione primo sprint", "Prima discussione sulle tecnologie utilizzabili"),
va be le modifiche si possono sempre fare, non è detto che tutto debba sempre essere retroattivo

2024-11-18 08:53 UTC, cvallott commented on RTB/documenti_esterni/verbali/2024-11-15.typ
> +  ordine_giorno: ("Discussione sulla modalità degli sprint", "Definizione primo sprint", "Prima discussione sulle tecnologie utilizzabili"),
yes intendevo per i futuri verbali, se no uno è messo in un modo e l'altro in un altro ancora, not good

2024-11-18 08:54 UTC, T-Brex requested changes

2024-11-18 08:54 UTC, T-Brex commented on RTB/documenti_esterni/verbali/2024-11-15.typ
> +  ordine_giorno: ("Discussione sulla modalità degli sprint.", "Definizione primo sprint.", "Prima discussione sulle tecnologie utilizzabili."),
Il "template" da seguire se non sbaglio è che ci devono essere i punti e virgola per tutti i punti tranne che l'ultimo, in cui invece c'è un punto

2024-11-18 08:56 UTC, MatteoSquarz commented on RTB/documenti_esterni/verbali/2024-11-15.typ
> +  ordine_giorno: ("Discussione sulla modalità degli sprint.", "Definizione primo sprint.", "Prima discussione sulle tecnologie utilizzabili."),
lascio la maiuscola all'inizio di ogni punto?

2024-11-18 08:56 UTC, MatteoSquarz commented on RTB/documenti_esterni/verbali/2024-11-15.typ
> +  ordine_giorno: ("Discussione sulla modalità degli sprint.", "Definizione primo sprint.", "Prima discussione sulle tecnologie utilizzabili."),
chiedo dato che senza la maiuscola non è molto bello

2024-11-18 08:59 UTC, T-Brex commented on RTB/documenti_esterni/verbali/2024-11-15.typ
> +  ordine_giorno: ("Discussione sulla modalità degli sprint.", "Definizione primo sprint.", "Prima discussione sulle tecnologie utilizzabili."),
Si, gli altri documento hanno questo stile:

```
1. Supporto agli issue tracking system;
2. Controllo di versione con git;
3. Processi di revisione del codice;
4. Test e integrazione continua.
```

2024-11-18 09:00 UTC, T-Brex approved these changes

2024-11-18 09:09 UTC, T-Brex approved these changes

2024-11-18 09:10 UTC, merged