Verbale del 18/11/2024
techminds-unipd/docs pull request #73
Opened 2024-11-18 17:30 UTC by tlazzarin

2024-11-18 19:50 UTC, cvallott requested changes

2024-11-18 19:50 UTC, cvallott commented on RTB/documenti_interni/verbali/2024-11-18.typ
> +  sommario: "Primo sprint planning",
manca il punto alla fine

2024-11-18 19:50 UTC, cvallott commented on RTB/documenti_interni/verbali/2024-11-18.typ
> +  È da segnalare che non è stato possibile tracciare la creazione delle #glossario[lables] per classificare le #glossario[issues] perché #glossario[Github] non lo permette.
- "labels", non "lables"
- l'ultima frase meglio specificare liste ed elenchi nei verbali (non in tutti i documenti)
- ampliare un po' di più, magari dire come andremo a svolgere lo studio delle tecnologie (in asincrono e chiedendo al team se ci sono dei dubbi particolari) 
- inserire inoltre come abbiamo deciso di gestire il riferimento alle parole del glossario (l'abbiamo messa come decisione ma secondo me meglio sottolineare che c'è una motivazione dietro tale decisione e soprattutto scrivere esplicitamente quale è stata la nostra scelta)

2024-11-18 19:50 UTC, cvallott commented on RTB/documenti_interni/verbali/2024-11-18.typ
> +    )
fare un sottoelenco con le issues specifiche per ogni tecnologia

2024-11-18 19:50 UTC, cvallott commented on RTB/documenti_interni/verbali/2024-11-18.typ
> +  ),
parole mancanti del glossario: non so bene come dobbiamo gestirle nei verbali, io direi di tenerne conto solamente dentro il riassunto (come hai già fatto in realtà). Per correttezza comunque te elenco tutte (pure quelle fuori dal riassunto).

analisi dei requisiti, casi d'uso, changelog, discord, glossario, issues, norme di progetto, piano di qualifica, sprint. 

tenendo conto solo della sezione riassunto invece manca solo la parola "sprint"

2024-11-18 20:28 UTC, tlazzarin commented on RTB/documenti_interni/verbali/2024-11-18.typ
> +  ),
> changelog, discord, glossario

Non penso sia necessario.

2024-11-18 20:33 UTC, cvallott commented on RTB/documenti_interni/verbali/2024-11-18.typ
> +  ),
concordo, dato che non abbiamo discusso con gli altri su questa cosa dei verbali (non ci era venuta in mente) ho scritto tutto per correttezza perché non si sa mai. per mia opinione personale basta tenere quelle del riassunto

2024-11-18 20:38 UTC, tlazzarin commented on RTB/documenti_interni/verbali/2024-11-18.typ
> +  È da segnalare che non è stato possibile tracciare la creazione delle #glossario[lables] per classificare le #glossario[issues] perché #glossario[Github] non lo permette.
> inserire inoltre come abbiamo deciso di gestire il riferimento alle parole del glossario

E come avevamo deciso? Una volta per sezione?

2024-11-18 20:44 UTC, tlazzarin commented on RTB/documenti_interni/verbali/2024-11-18.typ
> +  ),
Io direi che dal paragrafo 2 in poi si possono segnare, prima non serve anche perché sono sempre le stesse cose

2024-11-18 22:42 UTC, T-Brex requested changes

2024-11-18 22:42 UTC, T-Brex commented on RTB/documenti_interni/verbali/2024-11-18.typ
> +  Per l’autoformazione, abbiamo scelto di procedere in modo asincrono, con l'eventuale implementazione degli esempi presenti nella documentazione. In caso di dubbi, sarà possibile consultare i membri
Ripetizione spiegazione della decisione delle liste e degli elenchi:
 
```
\ Abbiamo deciso di comune accordo che le liste e gli elenchi nei verbali possono non terminare con punto e virgola. \ 
  In merito alla formattazione dei verbali, è stato concordato che le liste e gli elenchi possono terminare senza l’uso del punto e virgola.
```

2024-11-19 07:09 UTC, cvallott requested changes

2024-11-19 07:09 UTC, cvallott commented on RTB/documenti_interni/verbali/2024-11-18.typ
> +  Per l’autoformazione, abbiamo scelto di procedere in modo asincrono, con l'eventuale implementazione degli esempi presenti nella documentazione. In caso di dubbi, sarà possibile consultare i membri
non sono più messe in evidenza le parole del glossario dentro il riassunto

2024-11-19 08:51 UTC, cvallott requested changes

2024-11-19 08:51 UTC, cvallott commented on RTB/documenti_interni/verbali/2024-11-18.typ
> +      [#link("https://github.com/techminds-unipd/docs/issues/62")[Issue \#62]: Redazione diagrammi dei casi d'uso],
"casi d'uso" è parola del glossario

2024-11-19 08:51 UTC, cvallott commented on RTB/documenti_interni/verbali/2024-11-18.typ
> +  \ In merito alla formattazione dei verbali, è stato concordato che le liste e gli elenchi possono terminare senza l’uso del punto e virgola.
"verbali" è parola del glossario

2024-11-19 08:51 UTC, cvallott commented on RTB/documenti_interni/verbali/2024-11-18.typ
> +                  "Aggiunta labels su "+glossario[Github],
"glossario" è stata evidenziata due volte, togliere la seconda occorrenza. inoltre la parola "labels" ha la prima occorrenza qua

2024-11-19 08:51 UTC, cvallott commented on RTB/documenti_interni/verbali/2024-11-18.typ
> +  Si segnala che non è stato possibile tracciare la creazione delle #glossario[labels] per classificare le issues a causa di una limitazione di Github.
"labels" ha la prima occorrenza sopra, toglierla da qua

2024-11-19 08:51 UTC, cvallott commented on RTB/documenti_interni/verbali/2024-11-18.typ
> +      [#link("https://github.com/techminds-unipd/docs/issues/64")[Issue \#64]: React],
sarebbe meglio fare un sottoelenco con le issues da 64 a 67 dato che le issues specifiche sono state create dalla issue generale di autoformazione (se possibile da template, altrimenti va bene così)

2024-11-19 09:03 UTC, tlazzarin commented on RTB/documenti_interni/verbali/2024-11-18.typ
> +      [#link("https://github.com/techminds-unipd/docs/issues/64")[Issue \#64]: React],
Questo non ho idea di come farlo, può rimanere così.

2024-11-19 10:16 UTC, T-Brex requested changes

2024-11-19 10:16 UTC, T-Brex commented on RTB/documenti_interni/verbali/2024-11-18.typ
> +      [#link("https://github.com/techminds-unipd/docs/issues/68")[Issue \#68]: Redazione sprint 1 in piano di progetto],
"Sprint" è una parola del glossario

2024-11-19 10:24 UTC, cvallott commented on RTB/documenti_interni/verbali/2024-11-18.typ
> +      [#link("https://github.com/techminds-unipd/docs/issues/68")[Issue \#68]: Redazione sprint 1 in piano di progetto],
make sense dato che useremo quelle tecnologie, tanto poi ci pensa Giuse a scrivere tutte le definizioni dato che gli piace tanto LOL

2024-11-19 13:50 UTC, T-Brex approved these changes

2024-11-19 13:56 UTC, merged