Fix glossario
techminds-unipd/docs pull request #74
Opened 2024-11-19 14:12 UTC by tlazzarin

Fix #56

2024-11-20 19:41 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/introduzione.typ
> +Questo documento fornisce una descrizione esaustiva e dettagliata dei requisiti e i #glossario[casi d'uso] modellati dal gruppo Tech Minds per lo sviluppo del progetto _Automatizzare le routine digit
"requisiti" è parola del glossario

2024-11-21 14:43 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/introduzione.typ
"Norme di progetto" è parola di glossario

2024-11-21 14:54 UTC, T-Brex reviewed
Piano qualifica

- [ ] Indice di Gulpease sotto "2.2.1 metriche utilizzate"
- [x] Intelligenza artificiale sotto "1.3 scopo del prodotto"
- [x] Validazione in "1.1 Scopo del documento"
- [x] Verifica sotto "1.1 Scopo del documento"
- [x] workflow in "1.3 Scopo del prodotto"(ci sono tre occorrenze di workflow, in tale sezione, ma è segnata come parola del glossario la seconda, mentre dovrebbe essere la prima)


Norme di progetto
- [x] Capitolato sotto"1.4.1 Riferimenti capitolato" (viene messo

> Capitolato C3: https://www.math.unipd.it/~tullio/IS-1/2024/Progetto/C3.pdf.

ma la parola capitolato non viene evidenziata in alcun modo)

- [x] Processo sotto "3.2.1 caratteristiche e finalità"
- [x] Progetto sotto "1.1 scopo del documento"
- [ ]  Registro delle modifiche in "1.1 scopo del documento", anche se dopo si segnala chengelog, che è la stessa cosa (dovremmo forse scegliere una sola parola tra "changelog" e "registro delle modifiche"?)
- [x] Verbali sotto "3.1.4 Organizzazione dei documenti"
- [ ] Branch sotto "3.2.3 Gestione Repository"

2024-11-21 14:57 UTC, tlazzarin commented on RTB/documenti_esterni/analisi_requisiti/include/introduzione.typ
? glossario l'ho già segnato sopra

2024-11-21 15:04 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/introduzione.typ
si perchè, dato che non era stata modificata quella parte del file, non mi permetteva di 'riprenderla'. comuqnue vai nella sezione 'Riferimenti' (infatti il commento è messo più vicino possibile a quella parte) del documento analisi dei requisiti

2024-11-21 15:06 UTC, tlazzarin commented on RTB/documenti_esterni/analisi_requisiti/include/introduzione.typ
Ho trovato norme di progetto, 'glossario' dov'è?

2024-11-21 15:26 UTC, tlazzarin commented
>  la prima occorrenza di pull request e 10 parole prima rispetto a quella attualmente evidenziata (in 3.2.2 versionamento)

Lo so ma era già formattato in grassetto quindi avevo deciso di mettere l'occorrenza dopo dato che comunque era nella stessa riga. Se dici che va messa la prima la metto.

2024-11-21 16:12 UTC, T-Brex requested changes
Analisi dei requisti

- [x]  Capitolato sotto"1.4.1 Riferimenti capitolato" (viene messo
> Capitolato C3, Automatizzare le routine digitali tramite l’intelligenza generativa: https://www.math.unipd.it/~tullio/IS-1/2024/Progetto/C3.pdf;

ma la parola capitolato non viene evidenziata in alcun modo)

- [x] Caso d'uso sotto "1.1 scopo del documento"
- [x] Progetto sotto "1.1 scopo del documento"

Piano di progetto

- [x] processi sotto "1.1 scopo del documento"

2024-11-21 19:37 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/introduzione.typ
mea culpa, volevo dire 'capitolato' ma il mio cervello ha deciso di scrivere glossario

2024-11-21 19:39 UTC, cvallott commented
> * Caso d'uso sotto "1.1 scopo del documento"

questo è già evidenziato sopra "casi d'uso"

2024-11-22 11:11 UTC, cvallott approved these changes

2024-11-22 11:11 UTC, T-Brex approved these changes

2024-11-22 11:12 UTC, merged