Analisi dei rischi
techminds-unipd/docs pull request #77
Opened 2024-11-22 13:58 UTC by MatteoSquarz

Ignorate la sezione 1 incompleta dato che non è oggetto di questa issue. Feedback necessario su errori grammaticali o tipografici e sulla scelta dei rischi individuati.

2024-11-22 16:27 UTC, cvallott requested changes

2024-11-22 16:27 UTC, cvallott commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +I rischi personali sono identificati con la sigla "RP" seguita da un numero progressivo.\
"All’interno di questa categoria rientrano i rischi legati a problemi personali. Questi derivano dai nostri impegni individuali/difficoltà che possono verificarsi nel corso del progetto. 
Ogni rischio è identificato dalla sigla “RP” seguita da un numero progressivo." così l'indice di gulpease è contento. per il glossario aspettiamo versione definitiva. ho tolto la parte organizzativa perchè è gestita da una sezione apposta dopo.

2024-11-22 16:27 UTC, cvallott commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +    [Comunicare tempestivamente eventuali problemi di impegno al responsabile del progetto, in modo da poter trovare una soluzione che non comprometta il lavoro del team. Sfruttare al meglio la piani
ripetizione di "al meglio" nella stessa frase

2024-11-22 16:27 UTC, cvallott commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +#figure(
come colore di intestazione della tabella mettere l'arancione (nostro colore di bandiera...cit. gaggi)

2024-11-22 16:27 UTC, cvallott commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +  caption: [RP1 - Impegno di un membro del team inferiore a quanto dichiarato]
punto alla fine della caption (vale per ogni tabella, lo scrivo una volta sola)

2024-11-22 16:27 UTC, cvallott commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +  ),
indice di gulpease non conforme ma dato che siamo dentro ad un paragrafo di una tabella direi di non considerare questa cosa (e anche abbassare la soglia accettabile dal piano di qualifica, è stato sottovalutato)

2024-11-22 16:27 UTC, cvallott commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +All'interno di questa categoria vengono inseriti tutti i rischi che possono derivare da problemi organizzativi distinguendoli tra problemi di natura interna ed esterna.\
forse è più leggibile mettendola in forma di elenco, esempio 
"All’interno di questa categoria vengono inseriti tutti i rischi che possono derivare da problemi
organizzativi. Andremo a distinguerli tra:
- Problemi di natura interna: identificati con la sigla “ROI” seguita da un numero;
- Problemi di natura esterna: identificati con la sigla “ROE” seguita da un numero."

2024-11-22 16:27 UTC, cvallott commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +I rischi tecnologici sono identificati con la sigla "RT" seguita da un numero progressivo.\
indice di gulpease sotto la soglia accettabile, direi di abbassarlo sicuramente.

2024-11-22 16:27 UTC, cvallott commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +    ),
qui possiamo mettere che le tecnologie inizialmente scelte si sono rilevate non adatte alle nostre esigenze (se vedi piano di qualifica sezione 5.1 c'è il passaggio da latex a typst dove dobbiamo inserire il codice rischio associato). quindi magari questa cosa possiamo già metterla.

2024-11-22 17:00 UTC, T-Brex commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +#import "/template/template.typ": glossario
Mattew chiede di vedere errori grammaticali o tipografici e sulla scelta dei rischi individuati. e di non considerare la sezione 1

2024-11-22 17:04 UTC, cvallott commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +#import "/template/template.typ": glossario
Sorry non avevo visto

2024-11-22 20:17 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +La pericolosità verrà valutata su una scala costituita da 3 livelli dove si parte dal livello "Bassa", seguito dal livello "Media" fino ad arrivare al livello "Alta".\
sistemato "verranno", il paragrafo utilizzando farfalla per calcolo gulpease mi darebbe 57, a me sembra leggibile...
I codici per i rischi ho trovato più opportuno inserirli nella sezione dedicata, dato che una persona che legge questo documento potrebbe sentirsi disorientata se tutti i codici vengono presentati tutti insieme, quindi preferisco introdurre i codici progressivamente per ogni sezione.

2024-11-22 20:19 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +I rischi personali sono identificati con la sigla "RP" seguita da un numero progressivo.\
immesso la frase suggerita in sostituzione a quella che era presente prima

2024-11-22 20:23 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +    [Comunicare tempestivamente eventuali problemi di impegno al responsabile del progetto, in modo da poter trovare una soluzione che non comprometta il lavoro del team. Sfruttare al meglio la piani
risolto

2024-11-22 20:27 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +#figure(
risolto

2024-11-22 20:29 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +  caption: [RP1 - Impegno di un membro del team inferiore a quanto dichiarato]
risolto

2024-11-22 20:31 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +  ),
Se intendi paragrafo delle teniche di mitigazione farfalla mi dice indice pari a 70.

2024-11-22 20:38 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +I rischi tecnologici sono identificati con la sigla "RT" seguita da un numero progressivo.\
farfalla mi dice indice pari a 46... si tratta di 2 frasi non troppo lunghe in realtà non saprei

2024-11-22 20:52 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +    ),
Ora ho capito la situazione, ho scritto un nuovo rischio tecnologico per risolvere.

2024-11-23 14:59 UTC, T-Brex commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +La pericolosità verrà valutata su una scala costituita da 3 livelli dove si parte dal livello "Bassa", seguito dal livello "Media" fino ad arrivare al livello "Alta".\
Propongo questa modifica per una leggibilità migliore:
L’analisi dei rischi è una fase cruciale nella gestione di un progetto software, poiché permette di identificare, valutare e mitigare potenziali problemi che potrebbero compromettere il raggiungimento degli obiettivi. Un’analisi efficace consente al team di anticipare e affrontare in modo proattivo eventuali ostacoli, riducendo l’impatto di eventi negativi e migliorando la probabilità di successo del progetto. 
Di seguito verranno riportati tutti i rischi identificati, permettendo così una corretta classificazione. Per ogni rischio verrà indicata:
- Descrizione;
- Probabilità di occorrenza;
- Pericolosità che può avere sul progetto;
- Strategie di mitigazione adottate.
La probabilità di occorrenza verrà valutata su una scala da 1 a 5 dove 1 indica una probabilità molto bassa e 5 una probabilità molto alta.
La pericolosità verrà valutata su una scala costituita da 3 livelli dove si parte dal livello “Bassa”, seguito dal livello “Media” fino ad arrivare al livello “Alta”.

2024-11-23 15:01 UTC, T-Brex requested changes

2024-11-23 15:01 UTC, T-Brex commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +  table(
Non sarebbe meglio templatizzare la table? così da uniformarci con lo stile tra i vari file?

2024-11-23 15:04 UTC, T-Brex reviewed
L'indice di gulpease vabbene dato che abbiamo deciso di prendere come sito di riferimento: https://farfalla-project.org/readability_static/

2024-11-23 15:24 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +  table(
le tabelle potrebbero essere radicalmente diverse, penso ad esempio a quella del preventivo, dunque bisognerebbe rifarla da capo in ogni caso

2024-11-23 15:26 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +La pericolosità verrà valutata su una scala costituita da 3 livelli dove si parte dal livello "Bassa", seguito dal livello "Media" fino ad arrivare al livello "Alta".\
concordo

2024-11-23 15:38 UTC, MatteoSquarz commented on RTB/documenti_esterni/piano_progetto/include/analisi-dei-rischi.typ
> +  table(
cambiano numero colonne, forse colori a volte, il numero di intestazioni, dimensioni delle singole colonne.. non credo abbia un senso quindi

2024-11-24 12:29 UTC, T-Brex approved these changes

2024-11-24 12:38 UTC, cvallott approved these changes

2024-11-24 12:38 UTC, merged