User story 2
techminds-unipd/docs pull request #93
Opened 2024-12-04 18:26 UTC by Jacky8703

close #85

2024-12-04 19:10 UTC, T-Brex approved these changes

2024-12-07 13:42 UTC, cvallott requested changes

2024-12-07 13:42 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    caption: [Registrazione UC diagram]
punto dopo la caption

2024-12-07 13:42 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    node((2,0.5), [#image("../assets/actor.jpg") Database], stroke: 0pt, name: <db>),
forse è da togliere il db (almeno da come ho capito avete chiesto a cardin e ha detto così)

2024-12-07 13:42 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Database.
forse è da togliere il db (stessa motivazione del commento sopra)

2024-12-07 13:42 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +#figure(
aggiugnere nella figura anche i sottouse case (UC4.1, UC4.2, UC4.3, UC4.4)

2024-12-07 13:42 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. se la verifica fallisce si mostra un messaggio d'errore (@errore-registrazione).
da sistemare, per esempio con
1. attente l'esito della verifica da @creazione-username, @inserimento-email, @creazione-password e @conferma-password;
2. viene creato un nuovo account;
3. il nuovo account viene salvato nel database.

2024-12-07 13:42 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    - conferma password.
sostituire con
- utente inserisce username, email o password non valide in @registrazione.

2024-12-07 13:42 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    6. viene mostrato un messaggio d'errore.
da sistemare, per esempio con:
1. l'esito della verifica delle credenziali da @creazione-username, @inserimento-email, @creazione-password o @conferma-password non ha successo;
2. viene visualizzato un messaggio d'errore;
3. viene data la possibilità all'utente di riprovare a registrarsi.

2024-12-07 16:01 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    - conferma password.
metti anche in che use case li va ad inserire, se no è una ripetizione

2024-12-08 08:41 UTC, cvallott approved these changes

2024-12-08 09:03 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Viene mostrato un messaggio d'errore esplicativo.
è un elenco, quindi va il punto e virgola a parte sull'ultima voce

2024-12-08 10:35 UTC, merged