User story 3
techminds-unipd/docs pull request #95
Opened 2024-12-05 15:50 UTC by leosalvi03

close #86.
Non ho aggiunto nulla al changelog perché stiamo lavorando in tre su questo documento e il numero dipende dall'ordine di accettazione delle pr. Per questi motivi lascio questo onere ai verificatori.
Descrizione da inserire nel changelog: Redazione use cases relativi alla gestione dei servizi Google.

2024-12-06 19:47 UTC, cvallott requested changes

2024-12-06 19:47 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - Compie un'azione per la gestione dell'account Google associato (@gestione-servizi-google).
sottoelenchi con minuscola

2024-12-06 19:47 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. Notifica all'utente l'errore di comunicazione con Google e il mancato completamento dell'operazione corrente.
sottoelenchi con minuscola

2024-12-07 16:23 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/requisiti.typ
>  == Requisiti di qualità
Provo a spiegarmi meglio.
La funzionalità da sviluppare è volta a porter usare i vari servizi di Google (calendar, gmail, drive) come blocchi dei workflows. Per questo, si vuole poter associare il proprio account Google. Il login all'applicazione potrebbe non essere stato fatto con Google o con un account Google diverso da quello che si ma vuole usare nei workflows.
Se lo ritieni necessario, cambio la user story specificando che si tratta dei workflows

2024-12-07 16:32 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Google.
Quale sistema?
Il nostro sistema è qualcosa che posso cambiare in fase di design (quello di Google no), quindi non è stato inserito come attore. Allego un'immagine dalle slide di Cardin su come scegliere gli attori (spero si veda) ![Screenshot_20241207_173127_OneDrive.jpg](https://github.com/user-attachments/assets/8372a26a-1da9-46bc-acb3-72f4206af8cc)

2024-12-07 16:37 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/requisiti.typ
>  == Requisiti di qualità
non intendevo che giuseppe aveva tolto la descrizione delle user stories mettendo una tabella, quindi non ho capito se ci va sta tabella o la descrizione delle user stories

2024-12-07 16:38 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Google.
si sorrry ora ci sono, scusa

2024-12-07 16:42 UTC, leosalvi03 commented on RTB/documenti_esterni/analisi_requisiti/include/requisiti.typ
>  == Requisiti di qualità
Ora ho visto! L'avevo inserita ancora quando non c'era la tabella. Dopo cambio, grazie!

2024-12-08 08:58 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +  - Errore comunicazione Google (@errore-comunicazione-google);
l'ultimo punto dell'elenco deve finire con un punto

2024-12-08 08:59 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +
ultima voce di un elenco deve finire con un punto

2024-12-08 11:09 UTC, cvallott approved these changes

2024-12-08 11:10 UTC, T-Brex approved these changes

2024-12-08 11:10 UTC, merged