User story 5
techminds-unipd/docs pull request #96
Opened 2024-12-06 12:34 UTC by Giuseppe5000

Descrizione: Completato use case creazione workflow e salvataggio workflow.

2024-12-06 19:24 UTC, cvallott requested changes

2024-12-06 19:24 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    caption: [Creazione nuovo workflow UC diagram]
manca il punto alla fine della caption

2024-12-06 19:24 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   1. naviga nella pagina workflow.
va il punto e virgola e non il punto

2024-12-06 19:24 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   8. per ogni arco può descrivere un'automazione in linguaggio naturale.
può o deve descrivere?

2024-12-06 19:24 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    caption: [Salvataggio workdflow UC diagram]
manca il punto alla fine della caption, inoltre correggere la parola 'workdflow' con 'workflow'

2024-12-06 19:24 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   - Errore connessione database (@errore-connessione-database)
manca il punto finale

2024-12-06 19:24 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   3. viene visualizzato un messaggio d'errore.
sistemare punti e virgola al posto dei punti sulle prime due voci del sottoelenco

2024-12-06 19:24 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +- *Post-condizioni*:
le pre-condizioni non vanno messe?

2024-12-07 09:59 UTC, Giuseppe5000 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +   8. per ogni arco può descrivere un'automazione in linguaggio naturale.
Può, non è obbligato a farlo.

2024-12-07 10:00 UTC, Giuseppe5000 commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +- *Post-condizioni*:
Non posso assumere che sia loggato, questo errore potrei collegarlo anche a login volendo.

2024-12-07 13:47 UTC, cvallott commented on RTB/documenti_esterni/analisi_requisiti/include/use_cases.typ
> +    node((4,0), [#image("../assets/actor.jpg") Database], stroke: 0pt, name: <database>),
ma quindi questo db che facciamo? se no bisogna toglierlo da qua i think

2024-12-07 15:33 UTC, cvallott approved these changes

2024-12-08 11:24 UTC, T-Brex approved these changes

2024-12-08 11:24 UTC, merged